### ISSUE TITLE
Broken with new Firefox 36

### ISSUE THREAD

**Issue by igoutta** [YePpHa/YouTubeCenter#1509] opened 2015-02-27 03:12 UTC
Exactly the same as title says.

**Comment by ErdeFB** [comment] 2015-02-27 04:15
Possible duplicate of #1499.

**Comment by igoutta** [comment] 2015-02-27 09:50
It's exactly same issue.

**Comment by ErdeFB** [comment] 2015-02-27 10:27
Then please close this issue report by clicking the "close issue" -button at your earliest convenience, please.

**Closed** 2015-02-27 21:57 UTC
