### ISSUE TITLE
Comment countryflags is not showing

### ISSUE THREAD

**Issue by SINE** [YePpHa/YouTubeCenter#1701] opened 2015-04-29 07:16 UTC
Build 501

The countryflag before/after usernames in the comment section is not being displayed on Firefox 37.0.2. It used to work some while ago (I don't know exactly when it stopped working).

Resetting the YouTubeCenter settings and Firefox cache didn't help.

**Comment by SuperSajuuk** [comment] 2015-04-29 10:31
It's been missing for a long time now. I suspect YT simply removed the feature, or changed the way it's obtained and the script hasn't been updated to support the changes.

**Comment by SINE** [comment] 2015-04-29 11:40
It works on the video uploader's name next to the video title, so the feature must still exist.

**Comment by Inyokus** [comment] 2015-05-02 12:54
Duplicate of #1540.

**Closed** 2015-05-09 13:08 UTC
Labels: duplicate
