### ISSUE TITLE
Not appearing on Youtube

### ISSUE THREAD

**Issue by Tsagu** [YePpHa/YouTubeCenter#2202] opened 2016-03-09 00:21 UTC
Reinstalled Firefox and got back the lovely Youtube Center Dev branch, and it isn't working. It doesn't appear on youtube, I can't change any settings, and manually going into my extensions, clicking OPTIONS, it loads a new youtube, but no options menu pops up like it used to. 

Cog wheel is missing from upper right corner. 

I have latest version of Firefox, and the most up to date dev branch.

**Comment by ErdeFB** [comment] 2016-03-09 00:53
You either need to enable unsigned addons from about:config or use the greasemonkey version of the script. FF will eventually phase out unsigned addon support eventually so the userscript version is recommended. Also, please use the search next time as this is a dupe of a dupe of a dupe.

**Closed by ErdeFB** 2016-03-09 00:53 UTC
