### ISSUE TITLE
problem with "Enable shortcuts on page"

### ISSUE THREAD

**Issue by drummwill** [YePpHa/YouTubeCenter#1594] opened 2015-03-25 21:04 UTC
if "Enable shortcuts on page" is enabled, you are unable to type "space" or use the left and right arrow keys to navigate while typing in a comment, as if all keystrokes are catched by the video player and not in the comment box

**Comment by ErdeFB** [comment] 2015-03-25 21:06
Duplicate of #1546, please close.

**Closed** 2015-03-25 21:09 UTC
