### ISSUE TITLE
"Enable country for comments" and "Show country flags" don't work anymore.

### ISSUE THREAD

**Issue by bugreport0** [YePpHa/YouTubeCenter#1540] opened 2015-03-06 09:06 UTC

**Comment by yedey** [comment] 2015-03-06 23:29
Noticed that as well. Seems to be already fixed in the development version.

**Comment by bugreport0** [comment] 2015-03-07 08:52
Nope, still doesn't work as of Developer Version 492.

**Comment by rafaeldamasceno** [comment] 2015-03-11 18:25
Working for me.

**Comment by YePpHa** [comment] 2015-03-11 20:53
YouTube recently made a change where comments are directly embedded into the page instead of using the iframe element. This is good news as the performance will increase as the iframe counts as an extra page and will cause two instances of YouTube Center to run on one page.

**Comment by Inyokus** [comment] 2015-03-15 21:04
#1523 also seems to be caused by this. For me, comments on the watch page are in an iframe, while the comments on the All Comments page are directly on the page.

**Comment by NoXPhasma** [comment] 2015-03-20 02:47
The comment flags doesn't work for me too. Neither under the video nor on the all comments page. I'm using the latest dev build on FF 37 beta.

**Comment by ErdeFB** [comment] 2015-03-23 12:48
Seem to work fine on latest Chromium and YTC dev version at the time of writing.

**Comment by lotelegome29** [comment] 2015-03-30 08:45
Not working in Firefox 36.0.4. Ajax is being used to inject the comments onto the page. The page is sending a post request to https://www.youtube.com/watch_fragments_ajax and receiving them in json format. I don't see the country info anywhere. This feature was very useful... bummer.

**Comment by nikmurder** [comment] 2015-04-06 16:38
ff 37.0.1 w/build 497 as addon
same thing(

**Comment by lotelegome29** [comment] 2015-04-06 19:58
On the watch and all comments pages, the iframe and thus country/language/flag info came back...

**Comment by nikmurder** [comment] 2015-04-06 20:12
yep

**Comment by Inyokus** [comment] 2015-04-06 20:25
Not for me, comments are in the same page for watch page and all comments view.

**Comment by mzso** [comment] 2015-04-11 22:42
[**@YePpHa**](https://github.com/YePpHa) commented on [2015. márc. 11. 21:53 CET](https://github.com/YePpHa/YouTubeCenter/issues/1540#issuecomment-78369131 "2015-03-11T20:53:51Z - Replied by Github Comment Enhancer"):
> This is good news as the performance will increase as the iframe counts as an extra page and will cause two instances of YouTube Center to run on one page.
> 
> Edit: Change might not be for everyone.

It would be good news if they didn't still use the iframing thing for posting a new comment. It's incomprehensible... You can reply to another comment normally, but when you click in the texboxt for a new comment the iframe loads.

**Comment by Inyokus** [comment] 2015-04-12 11:17
At least for me, only the comment text box is in the iframe, not the comments themself, so that wouldn't be a problem.

**Comment by NoXPhasma** [comment] 2015-04-14 17:34
[**@Inyokus**](https://github.com/Inyokus) commented on [12. Apr. 2015 13:17 MESZ](https://github.com/YePpHa/YouTubeCenter/issues/1540#issuecomment-92035015 "2015-04-12T11:17:27Z - Replied by Github Comment Enhancer"):
> At least for me, only the comment text box is in the iframe, not the comments themself, so that wouldn't be a problem.

Same for me.

**Comment by lotelegome29** [comment] 2015-04-15 00:05
Interestingly enough if you open the text box iframe url and replace https://apis.google.com/u/0/_/widget/render/ytshare with https://apis.google.com/u/0/_/widget/render/comments it will load the comments with the flags.

**Comment by SuperSajuuk** [comment] 2015-04-19 15:57
The embedding of comments directly in the page is useful, but the only problem is that it's breaking with the keyboard commands. Every time I want to enter a space, it does it on the player, thinking I'm pausing the video, which means I have to reply to comments either via http://youtube.com/comments or the "All Comments" link.

**Comment by Zarggg** [comment] 2015-04-19 16:26
The developer and many of us here are well aware of the issue. Unfortunately, it's been a hard bug to smash due to YouTube using AJAX to inject the comments directly to the page. I'm not 100% certain of the details, but from what I have gathered, the script currently has no way of differentiating between the comment input box and the whitespace on the page. For this reason, it is suggested to disable ``Enable shortcuts on page`` if you do not need that specific functionality.

**Closed** 2015-05-09 14:52 UTC
Labels: bug

**Comment by SINE** [comment] 2015-05-13 06:38
It seems to be fiexed for me.

**Comment by audjack99aus8** [comment] 2015-07-16 13:45
how do we open the text box iframe url  as lotelegome29 commented please
