### ISSUE TITLE
Subscriptions inbox "Remove" button gone. (Grid subscriptions) [DUPE]

### ISSUE THREAD

**Issue by jacobmix** [YePpHa/YouTubeCenter#1667] opened 2015-04-16 13:39 UTC
The subscriptions inbox "Remove" button is gone. Now replaced with this http://prntscr.com/6ufe73 (Have to click on the 3 dots in the corner. Then a small window will pop-up with "Hide these videos")
This completely brakes the "Grid subscriptions" option. (Makes it look like this: http://prntscr.com/6uff0p)

~~Even BetterTube is having problems with this:
https://chrome.google.com/webstore/detail/better-tube/akbfgdngmldgocljaonhjnmnffdagpdl?hl=en
Pic: http://prntscr.com/6ufi01 (Remove button is gone. But everything else seems okay)~~

**Comment by Inyokus** [comment] 2015-04-16 14:38
Duplicate of #1640, already fixed in the [developer version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version)

**Comment by Yonezpt** [comment] 2015-04-17 09:07
@jacobmix Follow @Inyokus information and install the latest developer version which he linked.

**Closed** 2015-04-17 09:11 UTC
