### ISSUE TITLE
Thumbnails blocked from uploading

### ISSUE THREAD

**Issue by PureChaosX** [YePpHa/YouTubeCenter#1668] opened 2015-04-16 21:41 UTC
This seems to have been an ongoing issue for a while now.

Currently using the Developer Build 501, thumbnails will not upload while YTC is enabled. All that happens is "Try Again" appears where the Custom Thumbnail button was.

Once I disable YTC and upload again, the thumbnail successfully gets uploaded. It's quite annoying and frustrating having to disable YTC EVERY time I wish to upload a thumbnail.

**Comment by Inyokus** [comment] 2015-04-17 17:54
Appears to be a duplicate of #666. Are you using Firefox?

**Comment by ireun** [comment] 2015-07-11 10:48
Merging issues regarding this to one github issue: Check out issue number "1932".

**Closed by ireun** 2015-07-11 10:48 UTC
