### ISSUE TITLE
Like/Dislike button doesn't change its colour when clicked

### ISSUE THREAD

**Issue by xur86x** [YePpHa/YouTubeCenter#1553] opened 2015-03-11 18:40 UTC
When I click the like/dislike button it doesn't change to blue, like it normally does. The like gets registered, because when I reload it is blue.

Version is 492 with Firefox

**Comment by Hubcapp** [comment] 2015-03-11 20:39
Yep. I can confirm this issue. Firefox 38.

**Comment by Betsy25** [comment] 2015-03-11 21:43
+1 FF39

**Comment by F43nd1r** [comment] 2015-03-12 00:26
I confirm this too. Altough it doesn't always seem to toggle invisibly. It is not alwys registered for me...

**Comment by guiaurelio** [comment] 2015-03-12 02:08
It's happening in Chrome too... Version 493 Developer Build...

**Comment by emicom** [comment] 2015-03-12 15:29
On Pale Moon it is the same - doesn't count at all on YT page, but on embed pages (html5 player) it count.

**Comment by Primeey** [comment] 2015-03-12 20:33
I get the same problem and often it doesn't even register as a like or dislike if I refresh.

**Comment by Betsy25** [comment] 2015-03-12 20:40
Yeah, the script has been pretty much abandoned. We can only hope someone with the fork is willing to spend a little more time on it.

**Comment by Primeey** [comment] 2015-03-12 20:43
Abandoned? The last commit was yesterday then the 28th. That isn't Abandoned

**Comment by Hubcapp** [comment] 2015-03-12 23:26
Yeah, what the heck? YePpHa himself came and acknowledged this as a bug.

**Comment by Betsy25** [comment] 2015-03-12 23:38
Yeah, that's the only "work" being done lately.

**Comment by F43nd1r** [comment] 2015-03-12 23:46
Wtf dude? This isn't supposed to make youtube faster (although it does), it is supposed to make youtube customizable and fancy. And it is updated frequently (in the dev build channnel). What you said is wrong in all points.

**Comment by emicom** [comment] 2015-03-13 07:24
But, but... On full screen clicking on like does count, but then going back to normal window the share frame is on, though I did disable it in preferences. Interestingly enough on normal window (framed player) clicking on like button result in some failed connection to YT - so the indicator of Pale Moon shows.

**Comment by Blackbird88** [comment] 2015-03-13 08:58
Can confirm this as well.

**Comment by Leifman27** [comment] 2015-03-14 21:05
yep... u have to click it once or twice sometimes and refresh the page to see if it took effect..
it doesn't instantly pops up this thing saying "video added to liked" and changes color automatically like before the last 1 or 2 updates

**Comment by guiaurelio** [comment] 2015-03-15 20:06
It's happening de same with me @Leifman27

**Comment by digideth** [comment] 2015-03-17 07:22
it happens in Firefox 28 with YTC v2.1.7

**Comment by Hubcapp** [comment] 2015-03-17 08:50
@digideth This won't solve the problem, but make sure to use the latest developer version of YouTubeCenter. Other problems may be solved by this.

**Comment by xur86x** [comment] 2015-03-17 18:34
Somehow the problem is fixed for me now. Running build 493 with Firefox 36.0.1
Can anyone confirm this?

**Comment by Primeey** [comment] 2015-03-17 18:37
It can't just randomly be fixed. The dev has to fix it then push a update which he hasn't done so in a while. Still happening for me

**Comment by Primeey** [comment] 2015-03-17 18:37
It can't just randomly be fixed. The dev has to fix it then push a update
which he hasn't done so in a while. Still happening for me

**Comment by xur86x** [comment] 2015-03-17 18:41
Now I'm wondering what about my computer changed that made it work.

**Comment by guiaurelio** [comment] 2015-03-18 15:17
For me it's not fixed.
Youtube Center 493
Chrome 41.0.2272.89 m (64-bit)

**Comment by guiaurelio** [comment] 2015-03-18 19:04
Still the same...
Youtube Center 495

**Comment by guiaurelio** [comment] 2015-03-18 19:42
When I use FullScreen mode, the button works fine... Even though need reload to change the button colour... Youtube Center 495

**Comment by kancaras** [comment] 2015-03-19 01:02
Youtube Center 495
Still doesnt change color imediately, have to refresh page few times.

**Comment by emicom** [comment] 2015-03-19 12:20
Confirm - 495 - the bug stays.
Why is important like/dislike button? Because YT collect not only watched  videos, but liked as well. When Recommended tab in "What to Watch" is formed YT look at history and likes. When you've clean History Recommended go only to your subscription and likes (cleaning History clean search as well). IMO Dislike doesn't influence over search or Recommended, but Like does.

**Comment by ExcalibursZone** [comment] 2015-03-23 06:26
I am also having this issue in the latest version of YTC 495, Firefox 36.0.3 on Windows 8.1. I click the like button and nothing happens. I have to refresh and sometimes click the like button again then refresh again and it shows a like. Basic functionality like that should never be tampered with. I actually only use the script for two things: removal of DASH and default larger player size.

**Comment by random6969** [comment] 2015-03-23 22:01
This issue needs to be fixed ASAP in a new developer build, basic functionality such as liking / disliking a video is very annoying when it doesn't display properly.

**Comment by Qsaws** [comment] 2015-03-25 09:54
same thing here on firefox

**Comment by riderkick** [comment] 2015-03-28 19:10
It's working using userscript on firefox.

**Comment by ExcalibursZone** [comment] 2015-03-28 19:14
It is not working in version 36.0.4 of Firefox using the latest dev build of YTC. I have to click the like button, then refresh the page once or twice, sometimes as many as 3-4 times to get it to show up/stick. Highly frustrating.

**Comment by riderkick** [comment] 2015-03-29 08:20
I'm using Firefox 37.0 (beta), Youtube Center dev build 495 and Greasemonkey 3.1
It's working.

**Comment by YePpHa** [comment] 2015-04-01 17:33
Fixed in latest commit [ce5ae10](https://github.com/YePpHa/YouTubeCenter/commit/ce5ae1063833847750faad67627d7160048f9fc2).

**Closed by YePpHa** 2015-04-01 17:33 UTC
Labels: bug

**Comment by ExcalibursZone** [comment] 2015-04-01 17:51
Confirmed fixed: YTC User Script 496, FireFox 36.0.4. Thanks! :) (I wish there was a button to indicate done without opening the topic again...)

**Comment by ErdeFB** [comment] 2015-04-01 17:53
The issue report is still market closed if that is what you meant.

**Comment by guiaurelio** [comment] 2015-04-01 17:54
Confirmed fixed here too...
Chrome 41.0.2272.89 m (64-bit) Tampermonkey

**Comment by ExcalibursZone** [comment] 2015-04-01 17:55
Oh, excellent. Thanks for the hard work!
