### ISSUE TITLE
PSA: YTCenter seems to be dead. Use Youtube+

### ISSUE THREAD

**Issue by Eisys** [YePpHa/YouTubeCenter#2089] opened 2015-10-25 14:07 UTC
It's been months since an update and MANY things are broken. It would be nice if someone took over but I've heard that the code is complicated to work with so who knows..

There is another similar addon called [Youtube+](https://github.com/ParticleCore/Particle/).
It isn't quite as feature rich as YTC but it's being kept up to date and works very well.

If you aren't able to use YTC anymore because it doesn't work, I suggest you check out YT+. It might not be for everyone but I've been using it for a while and love it.

**Comment by Corruptinglyneedful** [comment] 2015-10-25 20:01
The last commit was on August 16, 2015 by Yeppah on the Master Branch.

It's not been months and months.

But yes, support has dwindled.

Jeppe got a full time job and it has been eating up his time and he basically does the same thing at his job, code stuff, so by the time he gets home he doesn't want to do anything.

It seems he doesn't wish to work on Youtube Center anymore.

So, instead of letting it die, someone here needs to pick it up and continue it.

Code is always complicated to work with, don't let that stop anyone.

Just do it or else YTC will die.

**Comment by IMNdi** [comment] 2015-11-04 18:15
PSA:

I tried your addon, it is:
a) broken
b) not playing well with other addons
c) laughably short on features. Making a video the size of the screen is not worth an addon.

There you go, a warm recommendation from me:

Stay well away from Youtube+.

**Comment by Zarggg** [comment] 2015-11-04 18:59
@Eisys: Please close this issue. Promotion and/or denigration of other projects is an inappropriate subject for an issue tracker.

**Comment by Corruptinglyneedful** [comment] 2015-11-04 19:43
I did not really like the alternative, either.

It's too feature poor and the dev is already whining about how it's getting clogged down with "useless" features.

Yes because being able to see the Like/Dislike ratio or the render quality, is useless -_-  He also has no way to disable the watch button.

It is really not a replacement.

**Comment by Yonezpt** [comment] 2015-11-04 20:58
@Eisys The publicity is appreciated, but not here, I hope you understand.

@Corruptinglyneedful YT+ is not meant to be a replacement of YTC, it never was: https://github.com/ParticleCore/Particle/issues/95#issuecomment-144881029

Every feature request is welcomed and might be added at a later stage, but adding every single feature would result in a catastrophic mess and nightmare to maintain. For that reason the requests are open to the author's choice, wether he finds it useful or not being the most important criteria. Each person making a request obviously finds it useful, it doesn't mean it will be for others too.

No one is annoying anyone, if it seems that way it is not intentional and I don't know where the idea of "whining" and "clogged with useless features" came from but I assure you that this is not correct.

**Closed by Yonezpt** 2015-11-04 20:58 UTC

**Comment by ParticleCore** [comment] 2015-11-04 21:15
@IMNdi I have received your review reporting the problems you found and posted a reply. Thanks to your feedback and another user's I was finally able to fix the missing icons problem which was only happening with the AMO add-on version. The 0.7.7 version with the fix for this is already available in the archive section for download if you want to try it again.

Also YT+ is not compatible with similar add-ons, Magic Actions being one good example because it interferes with many core functionalities which YT+ also needs. It was never meant to work along with other similar add-ons and it is focused on being light, not featured packed like other alternatives.

It would really make me happy if you could try it again. If you decide to try, in the future please try to contact me about any issues before rating the add-on at one start because of something that could have been fixed beforehand, and because of something that was never the focus of the software or advertised as (to be compatible with similar add-ons, such as Magic Actions).

**Comment by IMNdi** [comment] 2015-11-04 21:18
@ParticleCore Fixed.

**Comment by ParticleCore** [comment] 2015-11-04 21:36
@IMNdi Thank you, I am really glad that you decided to try it again. It is not surprising that YT+ does not work well with other add-ons for the reasons that I mentioned before, especially with YTC broken in many ways and especially because when all YTC settings are off it doesn't mean it isn't modifying the page, it still changes it regardless. YTC settings off does not mean the add-on is disabled which is why it still causes conflicts with YT+ with all settings off.

Your suggestions have been noted (especially the help link behavior improvement) and just wanted to address some of the other points you listed:

> Missing a few details (In night mode, there are controls in settings that are black on black) but I'd call that "working".

It is not surprising, the buttons were made in such a way that users with night mode userstyles could just invert the black buttons with a simple [css invert rule](https://davidwalsh.name/invert-colors-css), but it wasn't made to work with any background other than YouTube's default. This includes the Magic Action night mode, of course. Although I am happy to know that it works better than expected with Magic Actions, despite it not being made to be compatible with it.

> Glitches out if you click fullbrowser when video is popped to the side.

I never remembered to test that chain of events, will certainly try to fix this.

> If I set quality to 1080 and the video has 720p only, the Quality buttons shows nothing.

It is a YouTube bug present in the new HTML5 player. I reported on the same day I found it, but they haven't fixed it since. Still will try to see if I can find a workaround on our end.

In the future, if you want to, make any request for features or improvements, or even bug reports in my issue tracker: https://github.com/ParticleCore/Particle/issues

it will make it easier to informed of recent feedback and for tracking the problems as well.

Once again, thank you for all your help!

**Comment by Corruptinglyneedful** [comment] 2015-11-05 00:13
@Yonezpt I edited my post to more accurately reflect what I meant and remove things that you confirmed as not true.

To put it simply, if people are advertising you as an alternative, you are expected to be equal to or greater than the original idea they are coming from.  You aren't and this is what upsets people and also what upset me because I wasted my time for something that was pitched as an alternative to Youtube Center, when it isn't.  It's not even close.

I absolutely LOVE Youtube Center, but if it's dead, than we need an alternative that IS AS GOOD as Youtube Center is right now.  You've pretty much declared you are not going to be that alternative, yet you listed Youtube Center as a inspiration for you starting your own project.  So you are sending mixed signals.  There are about TWO Youtube addons that I can think of that are worth their salt, with the features that are provided.  One being YTC and the other is a Youtube addon on Chrome, I can't think of the name right now, but I showed Yeppah it one time and he said it was very good and feature rich, but Chrome Only.

The long and short of it, is this;

People are ALWAYS going to ask for more, more and more features.  You can't keep denying them forever, eventually people will get fed up and leave.

**Comment by Yonezpt** [comment] 2015-11-05 00:49
You are assuming that YT+ was created to compete with something when it was already well established that it was not, it is nothing more than a lighter option for those that want that. If people want more then YT+ is not it.

To be inspired by something does not mean that the person aims to be like it or better than its inspiration, at best you can only be certain that the inspiration gave birth to the project. It can be anything completely unrelated to the inspiration too, it is not mutually exclusive.

If people want to leave because they wanted YT+ to be something that was not meant to be then that's the best decision they can make, there's no reason to keep using something that the user doesn't like anymore. It is always best to look for something better that meets their needs.

It is like I said, YT+ is not a replacement of anything, it is an option for people that want just what YT+ offers. If there's something else they would like to see implemented but is not a must for them then they can just request. It might be included, it might not be, it might be included at a later time.

If there's any idea being officially given that YT+ is a replacement for similar add-ons then it is being misunderstood and it is incorrect. Furthermore, it is often reminded that YT+ focuses on being light and compact, not feature rich or anything similar.

In short, YT+ is for people that find the current feature set enough and want somethig that is light. It is not trying to compete with anything, it is not trying to be anything but itself and it is not trying to sound like something that it is not, and will never be as far as I can tell.


And in your new edited text you have the following:

>He also has no way to disable the watch button.

How so? It is clearly explained here that you can toggle it at will: https://github.com/ParticleCore/Particle/wiki/Features#info_bar
Or do you mean the watch later button? Because that is not any inability, it is simply something that isn't implemented. In fact if the user wants this he can just remove it with a simple userstyle rule. Can you show the reply confirming what you said?

And although you said you removed things that I confirmed as untrue then the following should not be present as well:

> the dev is not happy about it getting clogged down with "useless" features and seems adverse with people coming from Youtube Center and suggesting features that Youtube Center has.

And:

> Yes because being able to see the Like/Dislike ratio or the render quality, is useless

I clearly explained that saying that something isn't useful for that person does not mean that it is useless. If you can find any reply saying that the feature is useless I would really appreciate you showing me, otherwise what you said is not true.

I would also appreciate if you could provide examples of where the "seems adverse with people" is being conveyed because I can't find anything that could be constructed as being "adverse" towards anything or anyone, otherwise what you said about this is also not true.

**Comment by Corruptinglyneedful** [comment] 2015-11-05 03:07
You never actually said anything like that, sorry if it comes off that way.  It's more your attitude that speaks it for you. By this I mean;  I seen several replies to users asking for legitimate, to them, features from Youtube Center and you turned them down, citing that you did not want Y+ to become over saturated with features because than it would be hard to maintain and that if the user so wanted, they could just do this OTHER thing but you would take their suggestion into consideration. 

You're telling them to sod off, you're just being nice about it.

That's basic PR speech for "Go away, I do not care, go do this other thing, and stop bothering me."

As more and more people begin to look at you as a replacement to Youtube Center, these things will only continue increasing and becoming more and more annoying.

Here's the thing about that though.  The majority doesn't  care why you started the project or what it was meant to be.  The majority, especially about now are looking at you for ONE thing, to be a replacement to Youtube Center.  Your little buddy there, the one that's been singing your praises, didn't help with that situation, either.  He literally is pitching you as an alternative to Youtube Center.  That brings certain expectations when people hear that.  To find out that those expectations aren't going to get met, well that's upsetting.

That is one of the reasons I am so upset.  I wasted my time because it was pitched as an alternative to YTC and so I went into it with certain expectations, those of which were not met and when I realized you have no intention to meet those expectations, well it's just bitter disappointment and a waste of time.

Just like this whole damn conversation.  So this is going to be the last thing I say and there will not be a reply, so don't ask for one, because you won't get one.

If you do not aim or aspire to be greater or equal to the bigger dogs that people want you to become or compete with, than they will eventually tire and leave, which makes your project dead.  You might still be maintaining it but if the majority of your user-base leaves, well you'll be forgotten about and moved on from.

This is currently what is happening to World of Warcraft.  I use them because they are the biggest and most successful example but I do realize that the projects aren't the same, only the sentiment but just go with me here.  For years WoW refused to adapt, change, or add new features that people wanted, because it did not want them or find them useful.  It was being a stick in the mud.  Fast forward a few and competitors FINALLY came up with something that was better and exceeded user expectations.  So now WoW is loosing subs daily and Blizzy doesn't want to talk about it anymore, they are ashamed.  WoW attempted to recover by conceding and finally adapting and changing but it was too late.  It will die.  Eventually, it will get down to the point where the userbase paying for it, becomes more and more of an expense and a drain on Blizzy and they will shut it down.

Mark my words.  I give it MAYBE 10 years and Blizzy will shut WoW down, unless there is some fantastic turn-around.

The problem with your particular situationhere, is that your competitors ALREADY exist and have a better product than you do.  So, if you continue on the whole "THIS IS MY PROJECT AND I'LL ONLY DO WHAT I WANT WITH IT." well you're going be obsolete pretty quickly then, which maybe that's fine with you.  Frankly, I just think it's a waste of potential and time.

Anyways, I'm not going to start in on a rant about creators working for their user-base rather than themselves, that's not my point here.  Just try and think about what I have said or you can just chalk this all up to a jaded user experience, I don't really care.

I wish you success with w/e becomes of your project and no, I won't be around to see it.

PS: I have no qualms with you, think of this as advice.
PPS: This took me 15 minutes or longer to think up and type, so it's not something that was just bashed out on the keyboard in under 5 minutes.

**Comment by Yonezpt** [comment] 2015-11-05 09:06
>You're telling them to sod off, you're just being nice about it.

I am actually not, if i didn't want any more suggestions I would just close the issues and ignore them. I do always take them into consideration and I have already implemented at least 5 features, or more, which at first I didn't find them to be useful as well. I do go through all requests now and then to see if there's one I could add or not, if it is simple to do or not, worth it or not, etc.

Some times when I can tell the feature can be achieved from the user side easily (userstyles for example) I actually suggest them in case the user doesn't want to wait or really wants to have just that feature. Other times I even suggest other add-ons (userscripts) that do what they are looking for.

>As more and more people begin to look at you as a replacement to Youtube Center, these things will only continue increasing and becoming more and more annoying.

That is unfortunate, but I can't do anything about it other than clear things up like I have been doing here. I could do as many other developers do and not interact with the userbase other than for bug tracking, but I prefer to interact because I think there's more to gain than to lose for both sides like this.

>Your little buddy there, the one that's been singing your praises, didn't help with that situation, either.

Unfortunately it is something out of my control, he is also not the only one that considers YT+ to be a replacement for YTC, quite a few others do too and it is their opinion that this is true, not mine. If that's how they feel about it who am I to say that they are wrong? It is their opinion afterall and like I said, if they look at YT+ as something that is enough, even though it could have a bit more, then it fits what they were looking for.

>So this is going to be the last thing I say and there will not be a reply, so don't ask for one, because you won't get one.

I understand, I just want things to be clear so that something like this doesn't keep happening, at least not with you.

>If you do not aim or aspire to be greater or equal to the bigger dogs that people want you to become or compete with, than they will eventually tire and leave, which makes your project dead. You might still be maintaining it but if the majority of your user-base leaves, well you'll be forgotten about and moved on from.

If that is the case then it will sadden me, but it will not change what YT+ is because if I were to change then I would certainly get tired of it due to the intense maintenance and abandon the project.

I think I explained it better when I wrote this:

>It's not due to lack of interest but because I don't want to add more features unless I find them to be useful. The software has already reached a point where it has too many features for me to be comfortable with maintaining, especially with YouTube changing so often. If I were to add every feature that is requested I would very likely be having trouble now trying to maintain the software and keeping it light, eventually getting tired of it and abandoning the project.

>I would love to make a full feature packed software with all possible features requested by the users, but the frequent changes on YouTube do not permit it, at least not with just one person possessing limited time and programing knowledge.

>I hope you understand. 

https://greasyfork.org/en/forum/discussion/comment/17892/#Comment_17892

I do appreciate that you took the time to explain more of your thoughts, this will be a very useful conversation for other people that think of YT+ like you thought.

**Comment by Eisys** [comment] 2015-11-05 14:57
@Corruptinglyneedful  @Yonezpt 

I am sorry for all this.
I never meant that YT+ is an absolute replacement for YTC.
I just really like YT+ and wanted others to try it out if YTC wasn't working out for them anymore.
