### ISSUE TITLE
New developer builds don't work

### ISSUE THREAD

**Issue by Yaro96** [YePpHa/YouTubeCenter#1469] opened 2015-02-19 19:22 UTC
The newest builds doesn't work in firefox and html5 video, when oppening a video it doesn't load at all, and i can't play it, also, the settings button in the top right corner is missing in any video page as it onlavailable in the Youtube's "Main" and "Subscriptions" page. To watch any video, at all I had to downgrade to the version downloaded the 15th February

**Comment by Zarggg** [comment] 2015-02-19 19:30
In order to use the HTML5 in Firefox, you must enable Media Source Extensions. MSE is disabled by default in Firefox because it is not yet fully-implemented. See #1454 for information on how to enable it.

**Comment by Yaro96** [comment] 2015-02-19 21:46
Still, doesn't work. In the latest updates something went wrong, in a video tab, the video is resized to my Youtube Center Settings, but I can't play it at all, not in HTML5 nor in Flash, had to downgrade, and  Build #474 working as a charm, the only annoying thing is the Build #480 notification. Please check the update.

P.S. I'm not sure if the 474 build is the last working, it's just the last that I have saved to my PC, but I'm sure I had the same problem with 477 build, not only with 480.

**Comment by YePpHa** [comment] 2015-02-19 21:49
@Yaro96 I will try to investigate this, but could you perhaps try to find the last working commit ([userscript](https://github.com/YePpHa/YouTubeCenter/commits/master/dist/YouTubeCenter.user.js) or [Firefox addon](https://github.com/YePpHa/YouTubeCenter/commits/master/dist/YouTubeCenter.xpi)) as it would help a ton.

**Comment by Yaro96** [comment] 2015-02-19 22:09
Ok, I can confirm you that the last working version is the Build 474, the problem occurs already in the Build 475. Hope you can figure it out. I'm using the 35.0.1 version of Firefox.
Thank you.

**Comment by YePpHa** [comment] 2015-02-19 22:09
I will try to check the difference in build 474 and build 475.

**Comment by YePpHa** [comment] 2015-02-19 22:21
This is really weird. There is literally almost no difference:
```JavaScript
 // @id              YouTubeCenter
 // @name            YouTube Center Developer Build
 // @namespace       http://www.facebook.com/YouTubeCenter
-// @version         474
+// @version         475
 // @author          Jeppe Rune Mortensen <jepperm@gmail.com>
 // @description     YouTube Center Developer Build contains all kind of different useful functions which makes your visit on YouTube much more entertaining.
 // @icon            https://raw.github.com/YePpHa/YouTubeCenter/master/assets/icon48.png
 @@ -98,7 +98,7 @@
     if (typeof func === "string") {
       func = "function(){" + func + "}";
     }
-    script.appendChild(document.createTextNode("(" + func + ")(true, 0, true, 474);\n//# sourceURL=YouTubeCenter.js"));
+    script.appendChild(document.createTextNode("(" + func + ")(true, 0, true, 475);\n//# sourceURL=YouTubeCenter.js"));
     p.appendChild(script);
     p.removeChild(script);
   }
```

I might understand if it was build 474 where the issue started as I revamped the event system.

**Comment by YePpHa** [comment] 2015-02-19 22:24
I think perhaps that I need to look at your JavaScript developer console to figure out what the issue is. You can access the console by pressing CTRL + SHIFT + K. Please, post the content of the console here.

**Comment by AwesomeDonkey** [comment] 2015-02-19 22:27
Firefox 36, which will be released next week, *should* have MSE on by default.

**Comment by Yaro96** [comment] 2015-02-19 23:25
Here you are the console with the non working Build 475:
"Domain registered www.youtube.com." YouTubeCenter.js:26493
"[Property Wrapper] Wrapping the function undefined into a function wrapper." watch:2021
"[Property Wrapper] Property doesn't exists in parent, attaching trigger using `getter and setter`." watch:2021
"[External] Setting player configruation." watch:2021
"[Player modifyConfig] => watch" watch:2021
"[Player:setPlayerType] Requesting player type change to html5" watch:2021
"[Player:setPlayerType] Setting player type from null to html5" watch:2021
"[Player Type] HTML5" watch:2021
"[Player:getQuality] Most preferred available quality: hd720" watch:2021
"[Player Ratio] Player ratio set to 1.7777777777777777" watch:2021
"Chaning csi_page_type from watch,watch7ad to watch, watch7" watch:2021
"Keeping the aspect" watch:2021
"[Playlist] Disabled" watch:2021
"[HTML5 Player] Setting player theme to dark" watch:2021
"[HTML5 Player] Setting player progress color to red" watch:2021
"[HTML5 Player] Setting autohide to 1" watch:2021
"[SPF] ready" null watch:2021
"[Property Wrapper] Property doesn't exists in parent, attaching trigger using `getter and setter`." watch:2021
"[PageReadinessListener] At event => headerInitialized" "watch" watch:2021
"Language set to it-IT because it could not be auto-detected yet" watch:2021
"[PageReadinessListener] At event => bodyInitialized" "watch" watch:2021
"Adding player shortcuts to document" watch:2021
"[PageReadinessListener] At event => bodyInteractive" "watch" watch:2021
"[Thumbnail] Setup has begun..." watch:2021
"[Storage] Checking if settings have expired." watch:2021
"[Title Listener] "" => "Total Spoilage - Lord of the Rings"" watch:2021
"[Storage] Saving Settings" watch:2021
"[Tab Events] Sending new settings to other open tabs." watch:2021
"[Property Wrapper] Wrapping `create` function in a wrapper." watch:2021
"ytplayer.load() has been called." watch:2021
"yt.player.Application.create has been called" watch:10812
"Pointer: o" watch:2021
"Progressbar: xb" watch:2021
"Canvas: kb" watch:2021
"[Storage] Checking if settings have expired." watch:2021
"[Storage] Saving Settings" watch:2021
"[PageReadinessListener] At event => bodyComplete" "watch" watch:2021
"[Guide] Configurating the state updater!" watch:2021
"[PageReadinessListener] Stopping interval" watch:2021
"[External] Setting player configruation." watch:2021
"[Player modifyConfig] => watch" watch:2021
"[Player:setPlayerType] Requesting player type change to html5" watch:2021
"[Player:setPlayerType] Setting player type from null to html5" watch:2021
"[Player Type] HTML5" watch:2021
"[Player:getQuality] Most preferred available quality: hd720" watch:2021
"[Player Ratio] Player ratio set to 1.7777777777777777" watch:2021
"Chaning csi_page_type from watch, watch7_html5 to watch, watch7" watch:2021
"Keeping the aspect" watch:2021
"[Playlist] Disabled" watch:2021
"[HTML5 Player] Setting player theme to dark" watch:2021
"[HTML5 Player] Setting player progress color to red" watch:2021
"[HTML5 Player] Setting autohide to 1" watch:2021
"[Title Listener] "Total Spoilage - Lord of the Rings" => "▶ Total Spoilage - Lord of the Rings"" watch:2021
"[Title Listener] "▶ Total Spoilage - Lord of the Rings" => "Total Spoilage - Lord of the Rings"" watch:2021
"Domain registered www.youtube.com." YouTubeCenter.js:26493
"[PageReadinessListener] At event => headerInitialized" "watch" watch:2021
"Language set to it-IT because it could not be auto-detected yet" watch:2021
"[Tab Events] Sending new settings to other open tabs." watch:2021
"[Tab Events] Received updated settings from another tab." watch:2021
"Language set to it-IT because it could not be auto-detected yet" watch:2021
L’utilizzo di getAttributeNode() è deprecato. Al suo posto utilizzare getAttribute(). html5player.js:43
"Domain registered www.youtube.com." YouTubeCenter.js:26493
"[PageReadinessListener] At event => headerInitialized" "other" subscribe_embed:2021
"Language set to it-IT because it could not be auto-detected yet" subscribe_embed:2021
"[PageReadinessListener] At event => bodyInitialized" "other" subscribe_embed:2021
"Adding player shortcuts to document" subscribe_embed:2021
"[Property Wrapper] Wrapping the function undefined into a function wrapper." subscribe_embed:2021
"[Property Wrapper] Property doesn't exists in parent, attaching trigger using `getter and setter`." subscribe_embed:2021
"[PageReadinessListener] At event => bodyInteractive" "other" subscribe_embed:2021
TypeError: logoContainer is null subscribe_embed:25154
"[PageReadinessListener] At event => bodyComplete" "other" subscribe_embed:2021
"[Guide] Configurating the state updater!" subscribe_embed:2021
"[Player Update] Checking if player exist!" subscribe_embed:2021
"[PageReadinessListener] Stopping interval" subscribe_embed:2021
"YouTube configuration data is inaccessible; giving up on language auto-detection."

**Comment by Yaro96** [comment] 2015-02-19 23:28
And this is from the working Build 474 (same video):
"Domain registered www.youtube.com." YouTubeCenter.js:26432
"[Property Wrapper] Wrapping the function undefined into a function wrapper." watch:2021
"[Property Wrapper] Property doesn't exists in parent, attaching trigger using `getter and setter`." watch:2021
"[PageReadinessListener] At event => headerInitialized" "watch" watch:2021
"Language set to it-IT because it could not be auto-detected yet" watch:2021
"[PageReadinessListener] At event => bodyInitialized" "watch" watch:2021
"Adding player shortcuts to document" watch:2021
"[External] Setting player configruation." watch:2021
"[Player modifyConfig] => watch" watch:2021
"[Player:setPlayerType] Requesting player type change to html5" watch:2021
"[Player:setPlayerType] Setting player type from null to html5" watch:2021
"[Player Type] HTML5" watch:2021
"[Player:getQuality] Most preferred available quality: hd720" watch:2021
"[Player Ratio] Player ratio set to 1.7777777777777777" watch:2021
"Chaning csi_page_type from watch,watch7ad to watch, watch7" watch:2021
"Keeping the aspect" watch:2021
"[Playlist] Disabled" watch:2021
"[HTML5 Player] Setting player theme to dark" watch:2021
"[HTML5 Player] Setting player progress color to red" watch:2021
"[HTML5 Player] Setting autohide to 1" watch:2021
"[SPF] ready" null watch:2021
"[Property Wrapper] Property doesn't exists in parent, attaching trigger using `getter and setter`." watch:2021
"[PageReadinessListener] At event => bodyInteractive" "watch" watch:2021
"[Thumbnail] Setup has begun..." watch:2021
"[Storage] Checking if settings have expired." watch:2021
"[ActionPanel] Loading..." watch:2021
"[Player modifyConfig] => watch" watch:2021
"[Player:setPlayerType] Requesting player type change to html5" watch:2021
"[Player:setPlayerType] Setting player type from null to html5" watch:2021
"[Player Type] HTML5" watch:2021
"[Player:getQuality] Most preferred available quality: hd720" watch:2021
"[Player Ratio] Player ratio set to 1.7777777777777777" watch:2021
"Chaning csi_page_type from watch, watch7_html5 to watch, watch7" watch:2021
"Keeping the aspect" watch:2021
"[Playlist] Disabled" watch:2021
"[HTML5 Player] Setting player theme to dark" watch:2021
"[HTML5 Player] Setting player progress color to red" watch:2021
"[HTML5 Player] Setting autohide to 1" watch:2021
"Unknown element in settings" Object { type: 1, uniqueId: "DIV#watch8-secondary-actions.watch-secondary-actions.yt-uix-button-group SPAN[1]" } watch:2021
"Checking for updates in -0.0025599999999999998 hours..." watch:2021
"Checking for updates now..." watch:2021
"[Update] This is a dev build." watch:2021
"Checking for updates..." watch:2021
"[Title Listener] "" => "Total Spoilage - Lord of the Rings"" watch:2021
"[Storage] Saving Settings" watch:2021
"[Tab Events] Sending new settings to other open tabs." watch:2021
"[Storage] Checking if settings have expired." watch:2021
"[Storage] Saving Settings" watch:2021
"[Property Wrapper] Wrapping `create` function in a wrapper." watch:2021
"ytplayer.load() has been called." watch:2021
"yt.player.Application.create has been called" watch:10766
"Pointer: o" watch:2021
"Progressbar: xb" watch:2021
"Canvas: kb" watch:2021
"Got Update Response" watch:2021
"[Update] Current dev build #481. Your build number #474" watch:2021
"New update available" watch:2021
"[PageReadinessListener] At event => bodyComplete" "watch" watch:2021
"[Guide] Configurating the state updater!" watch:2021
"[PageReadinessListener] Stopping interval" watch:2021
"[Player Listener] Has begun the setup..." watch:2021
"[Player modifyConfig] => watch" watch:2021
"[Player:setPlayerType] Requesting player type change to html5" watch:2021
"[Player:setPlayerType] Type is already html5!" watch:2021
"[Player Type] HTML5" watch:2021
"[Player:getQuality] Most preferred available quality: hd720" watch:2021
"[Player Ratio] Player ratio set to 1.7777777777777777" watch:2021
"Chaning csi_page_type from watch, watch7_html5 to watch, watch7" watch:2021
"Keeping the aspect" watch:2021
"[Playlist] Disabled" watch:2021
"[HTML5 Player] Setting player theme to dark" watch:2021
"[HTML5 Player] Setting player progress color to red" watch:2021
"[HTML5 Player] Setting autohide to 1" watch:2021
"[Config Update] Updating as page https://www.youtube.com/watch?v=_JzACKa4joo" watch:2021
"[Storage] Checking if settings have expired." watch:2021
"[onYouTubePlayerReady] => updateConfig" watch:2021
"[Config Update] Updating as page watch" watch:2021
"[Player:getQuality] Most preferred available quality: hd720" watch:2021
"[Player:SetQuality] Setting quality to hd720" watch:2021
"[Player Listener] Event onPlaybackQualityChange was called with" Array [ "hd720", false ] watch:2021
"[Player:getQuality] Most preferred available quality: hd720" watch:2021
"[Player:SetQuality] Setting quality to hd720" watch:2021
"[Player Listener] Event onPlaybackQualityChange was called with" Array [ "hd720", false ] watch:2021
"[External] Setting player configruation." watch:2021
"[Player modifyConfig] => watch" watch:2021
"[Player:setPlayerType] Requesting player type change to html5" watch:2021
"[Player:setPlayerType] Type is already html5!" watch:2021
"[Player Type] HTML5" watch:2021
"[Player:getQuality] Most preferred available quality: hd720" watch:2021
"[Player Ratio] Player ratio set to 1.7777777777777777" watch:2021
"Chaning csi_page_type from watch, watch7_html5 to watch, watch7" watch:2021
"Keeping the aspect" watch:2021
"[Playlist] Disabled" watch:2021
"[HTML5 Player] Setting player theme to dark" watch:2021
"[HTML5 Player] Setting player progress color to red" watch:2021
"[HTML5 Player] Setting autohide to 1" watch:2021
"[Player Listener] Event onPlaybackQualityChange was called with" Array [ "hd720", false ] watch:2021
"[Player:getQuality] Most preferred available quality: hd720" watch:2021
"[Player:SetQuality] Setting quality to hd720" watch:2021
"[Player Listener] Event onPlaybackQualityChange was called with" Array [ "hd720", false ] watch:2021
"[Storage] Saving Settings" watch:2021
"[Title Listener] "Total Spoilage - Lord of the Rings" => "▶ Total Spoilage - Lord of the Rings"" watch:2021
"[Title Listener] "▶ Total Spoilage - Lord of the Rings" => "Total Spoilage - Lord of the Rings"" watch:2021
"Domain registered www.youtube.com." YouTubeCenter.js:26432
"[PageReadinessListener] At event => headerInitialized" "watch" watch:2021
"Language set to it-IT because it could not be auto-detected yet" watch:2021
"[ActionPanel] Loading..." watch:2021
"[ActionPanel] Setup has begun!" watch:2021
"[ActionPanel] Adding/Removing listeners" watch:2021
"[Tab Events] Sending new settings to other open tabs." watch:2021
"[Tab Events] Received updated settings from another tab." watch:2021
"Language set to it-IT because it could not be auto-detected yet" watch:2021
"[Player Listener] Event onStateChange was called with" Array [ -1, 1 ] watch:2021
"[Player Listener] Event onStateChange was called with" Array [ 3, 1 ] watch:2021
"[Player Listener] Event onStateChange was called with" Array [ -1, 1 ] watch:2021
"[Player Listener] Event onStateChange was called with" Array [ 3, 1 ] watch:2021
"[Player Listener] Event onStateChange was called with" Array [ 1, 1 ] watch:2021
"[Title Listener] "Total Spoilage - Lord of the Rings" => "▶ Total Spoilage - Lord of the Rings"" watch:2021
"[Title Listener] "▶ Total Spoilage - Lord of the Rings" => "Total Spoilage - Lord of the Rings"" watch:2021
"[Player Listener] Event onStateChange was called with" Array [ 3, 1 ] watch:2021
"[Player Listener] Event onStateChange was called with" Array [ 1, 1 ] watch:2021
"[Title Listener] "Total Spoilage - Lord of the Rings" => "▶ Total Spoilage - Lord of the Rings"" watch:2021
"[Title Listener] "▶ Total Spoilage - Lord of the Rings" => "Total Spoilage - Lord of the Rings"" watch:2021
L’utilizzo di getAttributeNode() è deprecato. Al suo posto utilizzare getAttribute(). html5player.js:43
"[Storage] Checking if settings have expired." watch:2021
"[Animated Thumbnail] Preloaded https://i.ytimg.com/sb/d0K436vUM4w/storyboard3_L2/M0.jpg?sigh=1yc9RdiIu2sn3xCRD6grPSRAl9k" watch:2021
"[Storage] Saving Settings" watch:2021
"[Tab Events] Sending new settings to other open tabs." watch:2021
"[Tab Events] Received updated settings from another tab." watch:2021
"Language set to it-IT because it could not be auto-detected yet" watch:2021
"[Player Listener] Event onStateChange was called with" Array [ 2, 1 ] watch:2021
"[Player Listener] Event onStateChange was called with" Array [ 1, 1 ] watch:2021
"[Title Listener] "Total Spoilage - Lord of the Rings" => "▶ Total Spoilage - Lord of the Rings"" watch:2021
"[Title Listener] "▶ Total Spoilage - Lord of the Rings" => "Total Spoilage - Lord of the Rings"" watch:2021
"YouTube configuration data is inaccessible; giving up on language auto-detection." watch:2021
"[Player Listener] Event onStateChange was called with" Array [ 2, 1 ] watch:2021
"YouTube configuration data is inaccessible; giving up on language auto-detection." watch:2021
"YouTube configuration data is inaccessible; giving up on language auto-detection." watch:2021

**Comment by Pontiac76** [comment] 2015-02-20 01:58
Downgraded to build 474 and the download button came back.  Going to keep this version around. ;)

**Comment by YePpHa** [comment] 2015-02-21 04:04
Could you test the newest developer version to see if it's fixed, because I just fixed an issue that might be the cause of this issue.

**Comment by Yaro96** [comment] 2015-02-21 07:18
Still, don't working, in all the newest builds, only some some Youtube Centre's features are enabled, like the flags near the comments and the video resize, the main problem is the video that can't be played(critical problem) and the missing settings icon, the one indicated in the screenshot, wich used to be in all the previous builds, including the 474.
If the changes between the 474 and 475 are not so relevant, can you try to revert them? Or perhaps you changed the way you compile the .xpi, or something?
![immagine](https://cloud.githubusercontent.com/assets/11079740/6313256/96639980-b9a1-11e4-9c8e-085a9d8950d4.jpg)

**Comment by YePpHa** [comment] 2015-02-21 14:42
Just to clarify things. Are you using the build from this commit https://github.com/YePpHa/YouTubeCenter/commit/49fbf58b6bfe97bf34e44395f891cfd3dbacf229 or https://github.com/YePpHa/YouTubeCenter/commit/077cdfac4af7fe75037fefccff6b65ead3aa70ab? If it's the first one, it's where I changed the internal event system.

**Comment by Pontiac76** [comment] 2015-02-21 15:10
Just had SVN update to XPI revision 1148 committed on Feb 21 @ 9:44 (Not sure if that is local or zulu), and still no go with any YTC buttons.  Tortoise doesn't show the same version numbers as you show here, however, looking at YouTubeCenter.user.js, which I just got now and has the same revision number, shows build 483.

I also meant to put in #1477 that when I scroll up to make the player browser-full-screen in 424.  Now what happens is the flash window disappears and does NOT return when scrolling down.

Might be related?

By the way, I have no other YT impacting add on.  I run a very clean browser.  The only other addons I have are Free Download Manager, LastPass, and XMarks.  I do have a bunch of codec based plugins, but doubt that has anything to do with it.

**Comment by Yaro96** [comment] 2015-02-21 15:27
I assure you that I'm using this one https://github.com/YePpHa/YouTubeCenter/blob/49fbf58b6bfe97bf34e44395f891cfd3dbacf229/dist/YouTubeCenter.xpi and it's working properly, and this https://github.com/YePpHa/YouTubeCenter/blob/077cdfac4af7fe75037fefccff6b65ead3aa70ab/dist/YouTubeCenter.xpi doesn't work.
![immagine](https://cloud.githubusercontent.com/assets/11079740/6314629/8738c9d6-b9e6-11e4-8965-c86a9149611a.jpg)

**Comment by YePpHa** [comment] 2015-02-21 15:44
@Yaro96 what does your developer console (CTRL + SHIFT + J/K) say when you're using the version that doesn't work?

**Comment by Yaro96** [comment] 2015-02-21 20:04
"[Storage] Checking if settings have expired." watch:2021
"[Storage] Saving Settings" watch:2021
"[Storage] Checking if settings have expired." watch:2021
"[Storage] Saving Settings" watch:2021
"[Tab Events] Sending new settings to other open tabs." watch:2021
"[Tab Events] Received updated settings from another tab." watch:2021
"Domain registered www.youtube.com." YouTubeCenter.js:26493
"[Property Wrapper] Wrapping the function undefined into a function wrapper." watch:2021
"[Property Wrapper] Property doesn't exists in parent, attaching trigger using `getter and setter`." watch:2021
"[PageReadinessListener] At event => headerInitialized" "watch" watch:2021
"Language set to it-IT because it could not be auto-detected yet" watch:2021
"[PageReadinessListener] At event => bodyInitialized" "watch" watch:2021
"Adding player shortcuts to document" watch:2021
"[External] Setting player configruation." watch:2021
"[Player modifyConfig] => watch" watch:2021
"[Player:setPlayerType] Requesting player type change to html5" watch:2021
"[Player:setPlayerType] Setting player type from null to html5" watch:2021
"[Player Type] HTML5" watch:2021
"[Player:getQuality] Most preferred available quality: hd720" watch:2021
"[Player Ratio] Player ratio set to 1.7777777777777777" watch:2021
"Chaning csi_page_type from watch,watch7ad to watch, watch7" watch:2021
"Keeping the aspect" watch:2021
"[Playlist] Disabled" watch:2021
"[HTML5 Player] Setting player theme to dark" watch:2021
"[HTML5 Player] Setting player progress color to red" watch:2021
"[HTML5 Player] Setting autohide to 1" watch:2021
"[SPF] ready" null watch:2021
"[Property Wrapper] Property doesn't exists in parent, attaching trigger using `getter and setter`." watch:2021
"[PageReadinessListener] At event => bodyInteractive" "watch" watch:2021
"[Thumbnail] Setup has begun..." watch:2021
"[Storage] Checking if settings have expired." watch:2021
"[Title Listener] "" => "WarOwl Channel Trailer"" watch:2021
TypeError: document.getElementById(...) is null watch:249
TypeError: playerOffset is null watch:20484
TypeError: playerAPI is null watch:22955
"[Storage] Saving Settings" watch:2021
"[Tab Events] Sending new settings to other open tabs." watch:2021
"[Storage] Checking if settings have expired." watch:2021
"[Storage] Saving Settings" watch:2021
"[Property Wrapper] Wrapping `create` function in a wrapper." watch:2021
"ytplayer.load() has been called." watch:2021
"yt.player.Application.create has been called" watch:10812
"Pointer: o" watch:2021
"Progressbar: xb" watch:2021
"Canvas: kb" watch:2021
"[PageReadinessListener] At event => bodyComplete" "watch" watch:2021
"[Guide] Configurating the state updater!" watch:2021
"[PageReadinessListener] Stopping interval" watch:2021
"[External] Setting player configruation." watch:2021
"[Player modifyConfig] => watch" watch:2021
"[Player:setPlayerType] Requesting player type change to html5" watch:2021
"[Player:setPlayerType] Setting player type from null to html5" watch:2021
"[Player Type] HTML5" watch:2021
"[Player:getQuality] Most preferred available quality: hd720" watch:2021
"[Player Ratio] Player ratio set to 1.7777777777777777" watch:2021
"Chaning csi_page_type from watch, watch7_html5 to watch, watch7" watch:2021
"Keeping the aspect" watch:2021
"[Playlist] Disabled" watch:2021
"[HTML5 Player] Setting player theme to dark" watch:2021
"[HTML5 Player] Setting player progress color to red" watch:2021
"[HTML5 Player] Setting autohide to 1" watch:2021
"[Title Listener] "WarOwl Channel Trailer" => "▶ WarOwl Channel Trailer"" watch:2021
"[Title Listener] "▶ WarOwl Channel Trailer" => "WarOwl Channel Trailer"" watch:2021
"Domain registered www.youtube.com." YouTubeCenter.js:26493
"[PageReadinessListener] At event => headerInitialized" "watch" watch:2021
"Language set to it-IT because it could not be auto-detected yet" watch:2021
"[Tab Events] Sending new settings to other open tabs." watch:2021
"[Tab Events] Received updated settings from another tab." watch:2021
"Language set to it-IT because it could not be auto-detected yet" watch:2021
L’utilizzo di getAttributeNode() è deprecato. Al suo posto utilizzare getAttribute()

**Comment by YePpHa** [comment] 2015-02-21 20:29
@Yaro96 seems like something changed in your console log from your previous logs. Seems like something happened with the fetching of some internal player elements. I'm very curious as to why YouTube Center failed. If you could save the YouTube watch page and send it to me either here or to my email: [jepperm@gmail.com](mailto:jepperm@gmail.com).

**Comment by Yaro96** [comment] 2015-02-21 21:34
save the .html page?

**Comment by YePpHa** [comment] 2015-02-21 22:23
@Yaro96 yes.

**Comment by Yaro96** [comment] 2015-02-22 15:27
Thank you, the latest Build 486 is working properly!

**Comment by YePpHa** [comment] 2015-02-22 15:51
@Yaro96 that's great news. Can others confirm this as well?

**Comment by Pontiac76** [comment] 2015-02-22 16:10
Confirmed working here as well.

**Closed** 2015-02-22 16:17 UTC
Labels: browser: Firefox, bug
