### ISSUE TITLE
Video "jumps" while not full screen.

### ISSUE THREAD

**Issue by HellishINC** [YePpHa/YouTubeCenter#1669] opened 2015-04-17 01:37 UTC
Using the latest build (501) video will "jump" (ie move up and down) while not in full screen.

Visual example: https://www.youtube.com/watch?v=P9bvZ9iuViA

This is using Opera 28.0.1750.51 on windows 8.1 x64. I used this same combination on Win 7 x64 without the issue exsisting. Turning off YTC does not reproduce the problem.

Log file: https://www.dropbox.com/s/46z5zchqp3engj2/000812.log?dl=0

If you need further information please ask.

**Comment by Yonezpt** [comment] 2015-04-17 09:12
This is being caused by YouTube's experiment with auto-hiding the controls while in theater mode. It should be fixed, at least it is not happening with me on Firefox and Chrome. Am I correct when I say that you mean this issue is only happening with Opera 28?

Try restting the YTC settings to default and/or disabling any other addon you have installed to rule out a possible conflict between extensions.

**Comment by HellishINC** [comment] 2015-04-17 09:39
I tried resetting it to no avail nor does disabling any other extensions.

I can't say for certain if it occurs with other versions but I can say that it did not do this while running windows 7. The only thing that changed was the OS, all extensions are the same versions as well as Opera.

**Comment by Yonezpt** [comment] 2015-04-17 09:53
Did you also try with a different browser? Also try changing the visibility options to see if there is one that can temporarily fix it, you can find it in Player > General > Auto-hide bar

The last option is to wait for the addon developer to check this issue.

**Comment by HellishINC** [comment] 2015-04-17 09:55
I was just trying that and setting it to auto-hide both (instead of default) allows it to work as usual.

Thank you for the suggestions.

**Closed** 2016-06-07 01:51 UTC
