### ISSUE TITLE
Is this now effectively Abandonware?

### ISSUE THREAD

**Issue by johnjjgraham** [YePpHa/YouTubeCenter#1999] opened 2015-08-10 09:18 UTC
There are so many issues plaguing YTC that are not getting fixed that by this point it seems like the project has been abandoned. It's gone from being updated almost daily to not at all. What's going on?

Half the time YTC doesn't even load anymore.

**Comment by Pontiac76** [comment] 2015-08-10 10:20
It works fine.  Use the developer version.

https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version

**Comment by johnjjgraham** [comment] 2015-08-10 12:48
I am. Works 50% of the time. Else it's just loads the non YTC Youtube page. And annotations never turn off, even when i've turned them off in YTC and in Youtube options.

**Comment by Nuriell** [comment] 2015-08-11 03:30
YouTube got another restyling breaking some things, like now the Auto-Hide Bar Option will not work, the bars always disappear.

**Comment by Eisys** [comment] 2015-08-11 10:55
It's really sad.. I absolutely love this addon. It works fine for me still though.
Wish someone would take over and update it more often.

**Comment by evetek** [comment] 2015-08-12 00:54
Dev build does not work properly on chrome, people are having lockups between 4-10 seconds when they visit youtube.

**Comment by Eisys** [comment] 2015-08-12 08:25
That happens to me but it's been happening for a long time and Im used to it.

**Comment by wayzhc** [comment] 2015-08-12 09:26
The thing is, Youtube has changed things almost weekly. More often than ever before.

**Comment by johnjjgraham** [comment] 2015-08-12 19:26
Pass the torch to someone who cares about the project

**Comment by Jaitsu** [comment] 2015-08-13 16:38
John - if you care so much about the project, then kindly go learn Javascript and fork this repository rather than insinuating that the developer doesn't care, especially when he's submitted code two days ago (the same day this issue was submitted). It's tough to keep up with a website that changes its code backend on a weekly basis with no warning and support 5 browsers, and fixing bugs isn't as simple as having a developer flip a switch.

**Comment by megascorcher** [comment] 2015-08-14 05:44
Dash playback is impossible to turn off now too.

**Comment by foss-** [comment] 2015-08-14 10:15
ireun, can you close this issue? It's not a bug per se, it's a rather random rambling contributing not too much cluttering the issue section.

As Jaitsu pointed out: if something is not working in the open source world, contribute code or visit https://freedomsponsors.org/ to raise incentives to get a specific problem you are seeing fixed faster. End of story.

**Comment by meldroc** [comment] 2015-08-16 14:53
I just got a new update today - seems to be running more smoothly now. Thank you, developers!

**Comment by SuperSajuuk** [comment] 2015-08-16 17:21
Abandonware is a program that has to have had no support for several years and the developer no longer making contributions. While the contributions to the repository are very sparse, this isn't abandonware. But I agree with the sentiments of the OP: there are too many broken aspects of the script for it to be of much use. I just removed it since it was wasting memory and freezing constantly, doing me no favours at all: the only thing I had it for was the auto-expanding description.

If someone could possibly pull this feature out of the script and make it separate, I'd appreciate it: I know absolutely nothing about the JS used in this script, so cannot do it myself (so please don't even bother to post a reply to this if your suggestion is to "do it yourself").

**Comment by rdamiano** [comment] 2015-08-16 20:46
Not sure which browser OP is talking about, but for Firefox users this add-on is and has been useless for the past few months.

Sure, it works, but give it a few minutes (and all of your memory) and it will become unresponsive and laggy. This issue has been known for months #1875, but has either been ignored or unnoticed by the developers.

Sadly, I'd call this abandonware, as the minor "superficial" updates that seem to occur every other week isn't fixing any of these types of major problems.

**Comment by Pontiac76** [comment] 2015-08-16 22:10
I'm ONLY a FireFox user and use this script DAILY for a LOT of YT videos
and I've NEVER experienced lag, memory issues, or anything of the sort.  At
all, ever.  My browser stays up constantly on one of my monitors while I
watch any number of videos a day.  I also run a very clean browser with no
fluff or addons or anything beyond this script.

If you're going to complain about software provided to you for free, with
no contribution from yourself other than to complain and whine about it,
then go get another tool to do what you need to do, or, pick up a
Javascript book and write your own.  Get this debate about whether this is
abandonware or not out of tracker.  It isn't wanted or needed.

**Comment by rdamiano** [comment] 2015-08-16 22:15
@Pontiac76 Not whining, stating facts. That's great that it works for you, but for many others that is not the case - I've even used a new FF profile to attempt to debug it, same issues. I have my own projects I take care of with my own sets of bugs and issues, no time to manage this one. Just trying to bring to attention a very critical bug to the developers that I haven't seen them even acknowledge.

**Comment by keLston** [comment] 2015-08-27 19:50
@Pontiac76 Feel free to provide proof. Multiple users have submitted this issue on Reddit, on Firefox official forums, on Firefox bugtracker, and on this addon's github tracing the memory leak to this specific addon.

You are the sole user indicating that there is absolutely no memory leak issue with this addon and Firefox. Using Firefox 40.0.2 with standard addons (Noscript, Adblock, Ghostery) and some non specific addons still allows my Firefox to run under 350MB. I can even spam 10 Youtube videos concurrently using a different Youtube addon and only get up to 1GB usage for Firefox but Firefox will release that memory as soon as I close those tabs. But as soon as I install this script, all it takes is opening two videos to get memory usage ballooning to over 850MB and gets worse quickly. Firefox will NEVER release that memory with this script running.

Prove your claim.

**Comment by Eisys** [comment] 2015-08-27 20:08
Guys, guys.. Just use Youtube+
https://github.com/ParticleCore/Particle/wiki

**Comment by RohithKumarSp** [comment] 2015-08-27 20:36
@eisys there's so much missing from that. and the video doesnt play if both extensions are enabled.

**Comment by ErdeFB** [comment] 2015-08-27 20:54
Please open a new ticket per issue or search if a issue report already exists and refrain from creating new tickets complaining about lack of updates. You can also check the link @Eisys posted.

Thanks for understanding.

**Closed by ErdeFB** 2015-08-27 20:54 UTC
Labels: invalid

**Comment by Pontiac76** [comment] 2015-08-28 00:40
@Kelston
 If you wanna call me out, cool.

https://youtu.be/yko-Tfgu6O0

**Comment by rdamiano** [comment] 2015-08-28 01:21
Gonna pop in and just say that back when I still used Youtube Center (2 months ago) with this FF bug, the lag/unresponsiveness would get worse over time (minutes) which I'm assuming corresponds to the memory leaking and amounting up. However, closing the Youtube tabs/windows would remedy the situation. Since the issue ticket is still live, I'll assume the bug still exists.

**Comment by vpontin** [comment] 2015-08-28 14:44
"Since the issue ticket is still live" @ErdeFB closed this

**Comment by rdamiano** [comment] 2015-08-28 19:23
@vpontin The issue we're talking about is #1875

**Comment by vpontin** [comment] 2015-08-29 06:52
So go there and comment, this issue are closed. Simply

**Comment by rdamiano** [comment] 2015-08-29 11:45
@vpontin Same to you.
