### ISSUE TITLE
Video Player not resizing right

### ISSUE THREAD

**Issue by SlimSterling** [YePpHa/YouTubeCenter#1849] opened 2015-05-28 01:44 UTC
When i go from default view to theater mode it causes the video to resize wrong were the video stays the same but the player is resized.

![imgur](https://i.imgur.com/Z3pUub2.png)

**Comment by andyb2** [comment] 2015-05-28 03:50
Many posts on this already

**Comment by SlimSterling** [comment] 2015-05-28 03:52
sorry i looked through a few pages of issues but didn't see anything

**Comment by andyb2** [comment] 2015-05-28 03:57
Everything below this is mostly about this problem.

**Comment by WPettersson** [comment] 2015-05-28 05:54
Both #1847 or #1844 discuss this problem.

**Comment by ireun** [comment] 2015-07-12 07:58
Yup, a duplicate of #1844, please write there if the problem still occurs.

**Closed by ireun** 2015-07-12 07:58 UTC
