### ISSUE TITLE
Lights Issue

### ISSUE THREAD

**Issue by LiamBM** [YePpHa/YouTubeCenter#1714] opened 2015-04-29 21:55 UTC
![screen shot 2015-04-29 at 22 51 31](https://cloud.githubusercontent.com/assets/11802806/7402298/a24a34ce-eec2-11e4-958a-8986186d8270.png)

Turning off the lights in google Chrome seems to leave a huge gap in between the player and the comments. Not sure if this is a huge issue considering I tend not to read the comments with the lights off, but thought i'd let you know anyhow.

**Comment by aztectornado** [comment] 2015-04-30 02:01
duplicate of #1696

**Comment by caeldom** [comment] 2015-04-30 14:23
Duplicate of #1708

**Closed** 2015-04-30 14:29 UTC
