### ISSUE TITLE
If I like a video and refresh the page, the like is gone

### ISSUE THREAD

**Issue by muyte** [YePpHa/YouTubeCenter#1935] opened 2015-07-09 02:07 UTC
Just noticed this now, not sure how long it has been an issue.

**Comment by SuperSajuuk** [comment] 2015-07-09 14:17
Can confirm this bug on latest developer version. The like displays the appropriate notifications and "looks" registered, but it is not being sent to YT to register on videos directly, which I've confirmed by clicking the like button several times on a video but the actual counter never goes up. Clearly seems to have been introduced from 527, as this didn't happen in 526, or YouTube broke the code again.

**Comment by ireun** [comment] 2015-07-10 09:29
Seems like a duplicate of #1933 i will close this issue, please tell me if this still ocours..

**Closed by ireun** 2015-07-10 09:29 UTC
Labels: bug
