### ISSUE TITLE
How can I totaly uninstall youtubeCenter in firefox? there is a problem

### ISSUE THREAD

**Issue by aviadhhh** [YePpHa/YouTubeCenter#1878] opened 2015-06-06 11:59 UTC
After I removed the addon from firefox it still shows the page with no comments and with no suggestion (videos). also I clean all the history. screenshot attached. 
http://i.imgur.com/O6UXgOI.png

**Comment by Yonezpt** [comment] 2015-06-06 21:12
If you are not the same user as this one which reported the exact same YouTube problem: http://www.reddit.com/r/youtube/comments/38rl3k/why_cant_i_view_comments_or_related_videos/

Then I suggest you also try what worked for him. If YTC has been removed then another add-on is causing that issue, I also am not aware of any YTC feature that can remove suggested videos so that's a big hint on this not being caused by YTC in any way.

**Comment by aviadhhh** [comment] 2015-06-07 06:24
Thank you for your answer. uBlock case the problem.

**Comment by Zarggg** [comment] 2015-06-08 00:07
@aviadhhh: Please close this issue as it is not related to YTC.

**Closed** 2015-06-08 04:21 UTC
