### ISSUE TITLE
Subscriptions Page Unusable

### ISSUE THREAD

**Issue by ftnirp** [YePpHa/YouTubeCenter#1648] opened 2015-04-11 15:38 UTC
As of a day or two ago the subscriptions page has become unusable.  It shows only video thumbnails, but in the "regular" Youtube list layout, not the grid layout.  No descriptions, no video titles, nothing but the thumbnails.

I'm on the latest version of Chrome.

Thanks.
![capture](https://cloud.githubusercontent.com/assets/11901570/7101968/483a4dac-e03f-11e4-839b-2aabbfe0a5a5.PNG)

**Comment by Zarggg** [comment] 2015-04-11 16:21
YouTube has changed the underlying code of the subscriptions page. If you disable YTC you will see that there is no longer a "grid" view. My guess is that YouTube is trying to streamline playlist/channel/subscription pages to look similar to each other (if not the same).

It's already been reported. Once someone can come up with a patch for it, it will probably be merged in.

**Comment by TetraSky** [comment] 2015-04-11 16:38
Seems to be fixed for me in the latest dev build 498.

**Comment by Zarggg** [comment] 2015-04-11 16:47
@TetraSky: Confirmed fixed for Chrome 41, Userscript via Tampermonkey.

**Closed** 2015-04-11 18:54 UTC
