### ISSUE TITLE
Fill Screen (resize) no longer working.

### ISSUE THREAD

**Issue by crzyflyinazn** [YePpHa/YouTubeCenter#1844] opened 2015-05-26 23:41 UTC
Running developer build 525 and this issue just popped up today. I haven't touched any of my settings in the extension or in chrome.

* Chrome 43.0.2357.65 m

![yt](https://cloud.githubusercontent.com/assets/10094587/7825777/f5a4a0d8-03c5-11e5-8c8b-61886be1c5f6.jpg)

**Comment by Rauvagol** [comment] 2015-05-26 23:48
Broken in firefox too, no changes made by me

**Comment by pscho** [comment] 2015-05-27 00:23
Firefox: http://i.imgur.com/F09zmRO.png

**Comment by nallar** [comment] 2015-05-27 00:23
Confirmed on Safari 8.0.6 with build 525.

**Comment by subnomo** [comment] 2015-05-27 00:30
Ditto. Chrome 44.0.2403.9 dev-m.

**Comment by hoboX10** [comment] 2015-05-27 01:35
Same issue, wonder what YouTube changed this time, sigh...

**Comment by Cephsus** [comment] 2015-05-27 01:50
Wish thouse YT updates were optional.

**Comment by TetraSky** [comment] 2015-05-27 02:00
Not just in "fullscreen", changing the player size with YTC result in what the OP posted.
But, this is only when using the HTML5 player. If you force Flash with YTC, the video is properly sized.
Firefox 38.0.1 / YTC dev build 525

**Comment by megascorcher** [comment] 2015-05-27 02:15
Same in Chrome 43.0.2357.81 m
http://i.imgur.com/8uIwb50.png

**Comment by guiaurelio** [comment] 2015-05-27 02:33
Same in Chrome 43.0.2357.81 m
YTC Developer Version 525

**Comment by rayman89** [comment] 2015-05-27 02:34
Happens with html5 with flash at least in my case doesn't happen. Try the flash option if you have predefined instead.

BTW does anyone know if you can hide the header forever unless you go to the top of the page isntead of just when it's playing?

**Comment by guiaurelio** [comment] 2015-05-27 02:37
Even if works fine with Flash, this is a issue that needs to be fixed, isn't it? :)

**Comment by rayman89** [comment] 2015-05-27 02:39
Yeah but any info helps to the dev to be able to allocate the problem and also gives people interested a quick fix.

**Comment by guiaurelio** [comment] 2015-05-27 02:40
I agree :+1:

**Comment by ButchDeLoria** [comment] 2015-05-27 03:01
Firefox 38.0.1
YTC Dev Build 525
Also getting this with HTML5 video enabled. Google must have released another update just to screw up extensions.

**Comment by crzyflyinazn** [comment] 2015-05-27 03:41
Yup, forcing flash fixes the issue. But my HTML 5 D:

**Comment by allexradu** [comment] 2015-05-27 04:29
I've got the same problem.
<a href='http://postimg.org/image/mxe5shj9t/full/' target='_blank'><img src='http://s16.postimg.org/57ch7g5p1/fit_to_content.png' border='0' alt="fit to=content" /></a><br /><a target='_blank' href='http://postimage.org/'>images</a><br /><br />

You can view all my debugging information here http://pastebin.com/TjEzLrcr

**Comment by CaptainLeChimp** [comment] 2015-05-27 07:07
Same bug with Fullscreen Top Player function
Version 43.0.2357.81 m (64-bit) latest userscript

![ytcbug_scrolltowindow-](https://cloud.githubusercontent.com/assets/10194458/7830683/bfb38fc2-044f-11e5-957b-07b744aee077.JPG)

**Comment by KamranMackey** [comment] 2015-05-27 08:37
Another stupid YouTube change, as usual. @YePpHa please fix it.

**Comment by SuperSajuuk** [comment] 2015-05-27 10:13
It appears that the fix originally created by @Yonezpt is now not loading as it should. Probably a YT change that broke parts of it, but I have noticed that it **does** sometimes load, but not consistently.

**Comment by KamranMackey** [comment] 2015-05-27 11:29
@SuperSajuuk Maybe you could try fixing it?

**Comment by SuperSajuuk** [comment] 2015-05-27 11:38
@KamranMackey Sorry, I don't know the codebase for this extension. I know JS and things like that, but nowhere near enough to fix bugs in extensions. You'll need to wait for @YePpHa or @Yonezpt to see the ticket and create the fix. Sorry!

**Comment by megascorcher** [comment] 2015-05-27 13:45
@allexradu entering a height for the Fit to Content preset doesn't fix anything for me.

**Comment by Cellane** [comment] 2015-05-27 17:12
The new HTML5 player doesn't seem to be affected by this (judging by my tiny amount of testing and all of the screenshots above using the old HTML5 player), you can enable it [here](http://www.youtube.com/testtube) as a temporary fix, I guess.

**Comment by Primeey** [comment] 2015-05-27 17:20
Yup Cellane is correct. Use the new player as a workaround until @YePpHa fixes it.

**Comment by Seraphex45** [comment] 2015-05-27 17:24
Running on Firefox Aurora x64 and getting this issue as well.

**Comment by SuperSajuuk** [comment] 2015-05-27 17:43
@Cellane Good to know, but I despise the new player because it removes 40px in height and everything is oversized unnecessarily. I would prefer a fix on the older player, but thanks I guess..

**Comment by mattprg** [comment] 2015-05-27 17:55
@Cellane Thanks, it fixed the issue. I also like the progress bar's transparency.

**Comment by Yonezpt** [comment] 2015-05-27 18:00
My fix is still working correctly, but for some reason it is not being applied as/when it should. Using the flash player or the new html5 player are alternative fixes at least until a fix for this specific problem can be created.

**Comment by rayman89** [comment] 2015-05-27 18:55
@Yonezpt What about using a timer?

**Comment by Yonezpt** [comment] 2015-05-27 19:15
@rayman89 A timer won't work, it needs to hijack the code responsible for the player creation when the player is about to be created, otherwise my fix will not be used if it is injected after the player is already created. The other two issues you mentioned are not related to this one and should be posted in the respective issue or create a new one for them if needed.

**Comment by MammothJerk** [comment] 2015-05-27 21:47
waterfox 38.0
![](http://puu.sh/i2Vgc/0988138e8a.jpg)

**Comment by KamranMackey** [comment] 2015-05-27 21:52
@MammothJerk Switch to the new player, it fixes the problem. Click [here](https://youtube.com/testtube) to enable it.

**Comment by MammothJerk** [comment] 2015-05-27 21:57
does not fix it, the player is just black with no options now

**Comment by KamranMackey** [comment] 2015-05-27 22:04
@MammothJerk Try resetting your YouTube Center settings, because it's working just fine for me in the latest dev build of Google Chrome.

**Comment by Yonezpt** [comment] 2015-05-27 22:04
@KamranMackey he probably has autoplay disabled which has been buggy lately.

**Comment by KamranMackey** [comment] 2015-05-27 22:06
@Yonezpt Probably. Anyway, do you think you could probably fix the issue in the old HTML5 player? While I like the new one and the transparency of the player bar, the player bar is just too big when in fullscreen.

**Comment by Seraphex45** [comment] 2015-05-27 22:10
I've confirmed that disable auto-play is what's causing the player to be a black box using Cellane's solution with the new HTML5 player on Firefox Dev 64-bit.

**Comment by Yonezpt** [comment] 2015-05-27 22:35
It seems that my fix is no longer working, although it looked like it was working for me, I'll try to find a new method.

**Comment by Yonezpt** [comment] 2015-05-27 22:49
@YePpHa It looks like they finally ditched that horrible hardcoded system they had before and replaced with the one being used in the new transparent player which is regulated by the `matchMedia` method. Setting it to false works just as great.

Regulating function is the following one:

````javascript

    f.wb = function() {
        var a = this.app.X();
        if (window.matchMedia) { // <- Here's the beautiful condition, so much better for us developers!
            if ((a.jb || a.$a) && window.matchMedia("(width: " + window.innerWidth + "px) and (height: " + window.innerHeight + "px)").matches)
                return new H(window.innerWidth, window.innerHeight);
            if (DK(a) && "blazer" != a.j && !a.$a) {
                a = a.experiments.V;
                if (window.matchMedia(m8.C).matches)
                    return new H(426, a ? 280 : 240);
                var b = this.app.ka;
                if (window.matchMedia(b ? m8.o : m8.j).matches)
                    return new H(1280, a ? 760 : 720);
                if (b || window.matchMedia(m8.A).matches)
                    return new H(854, a ? 520 : 480);
                if (window.matchMedia(m8.B).matches)
                    return new H(640, 
                    a ? 400 : 360)
            }
        }
        return new H(this.element.clientWidth, this.element.clientHeight)
    };
````

To everyone here, just be patient until YePpHa applies the fix, until then make use of the suggested temporary fixes: either use the flash player or the new transparent player with autoplay disabled.

To the YouTube team member that might be watching this issue forum and, thank you for making it easier to develop software for your service.

**Comment by SleepyPrince** [comment] 2015-05-28 03:54
I wrote a Stylish script to fix that temporarily
```css
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("youtube.com") {
  .video-stream.html5-main-video{
    width: 100% !important;
    height: auto !important;
  }
}
```

**Comment by Yonezpt** [comment] 2015-05-28 07:48
@SleepyPrince That will only make the video fill the space, but all of the annotations and the seek bar will not work/display correctly.

**Comment by allexradu** [comment] 2015-05-28 09:45
@megascorcher

HOW TO FIX IT:
Step 1:
Settings > Player > General (1st tab) > Player Type > Aggressive Flash
Step 2:
Settings > Player > Player Size > Fit to Content :
Width: 1066
Height: 595

**Comment by SnowGabe** [comment] 2015-05-28 10:48
@Yonezpt Allowing autoplay didn't solve the black screen issue.

**Comment by Yonezpt** [comment] 2015-05-28 12:30
@SnowGabe I suggested two temporary workarounds, if one didn't work for you then try the other.

**Comment by YePpHa** [comment] 2015-05-28 17:59
@Yonezpt I see. For the new HTML5 player I have simply resolved to remove the `matchMedia` API for YouTube. However, as this is a kind of brutal way of doing it (removing browser API) I resolved to only do it for the new HTML5 player:
```JavaScript
function fixPlayerSize() {
	if (isNewPlayer()) {
		window.matchMedia = null;
	} else {
		patchDetour();
	}
}
```

The solution to this is to always remove the `matchMedia` API. However, before I can do this I just need to setup my new computer to be able to compile Safari extensions.

**Comment by Yonezpt** [comment] 2015-05-28 18:07
Correct, since both player versions now use the same condition, the solution for the new player now works for the default player, so you don't even have to check which player the user has, simply nuking `matchMedia` will solve all of our resizing problems.

**Comment by rayou** [comment] 2015-05-29 16:19
@Seraphex45 try press spacebar if you have black box with new player.

**Comment by SnowGabe** [comment] 2015-05-29 17:12
@Yonezpt I'm using the new HTML5 player, doesn't work. I won't go back to Flash because of privacy issues, I don't even have Flash Player installed. "layers.offmainthreadcomposition.enabled" is set to true.

**Comment by AndrewTheWookie** [comment] 2015-05-30 02:32
The only way I got it to work with the new HTML5 player was disabling "Prevent Auto-Play" and "Prevent Auto-Buffering."

**Comment by SnowGabe** [comment] 2015-05-30 09:37
@AndrewTheWookie Thank you, I forgot to turn off "prevent auto-buffering".

**Comment by DejayRezme** [comment] 2015-05-30 18:08
Thanks Cellane the new player fixed it for now! And thank you YePpHa for your great work, YTC really makes youtube much better.

**Comment by Cyguard** [comment] 2015-05-31 04:17
slight problem with the html5 player. playlists dont function like they should. by that i mean it doesnt go to the next video on its own. this is likely not an issue with YTC though.

**Comment by KamranMackey** [comment] 2015-05-31 14:22
@Cyguard Well, they are still working on it. What do you expect? :smiley:

**Comment by Cyguard** [comment] 2015-05-31 21:39
@KamranMackey upon further testing it is YTC at fault for not going to the next video in the list. not that big a deal though.

**Comment by bdawg923** [comment] 2015-06-07 03:22
Thanks for the testtube player suggestion. That fixed it. Hopefully there's a real fix soon. :)

**Comment by MammothJerk** [comment] 2015-06-09 09:25
the testtube fix worked for me but now i cant play the video as usual.

with autoplay off which is how i prefer it, whenever i open a video its just all black, and i have to press spacebar for the video to play and it wont buffer unless i press spacebar

in the old player it would buffer while still not playing.

if i turn the prevent autoplay off in the ytc options when i open several tabs they will all start playing and lagg my browser to hell, even when i have the "Only one player instance playing" turned on
very annoying when you use your tv for youtube and you dont have a keyboard handy.

**Comment by ngld** [comment] 2015-06-09 22:40
I can confirm that [YePpHa's fix](#issuecomment-106532646) works. I replaced line 10989 with ```if(1) {``` to test it.

**Comment by markreg** [comment] 2015-06-12 07:35
@ngld Perfect fix. Just replace "if(isNewPlayer())" with "if(1)". Problem solved.

**Comment by MammothJerk** [comment] 2015-06-12 08:48
@ngld Worked for me aswell

**Comment by Yonezpt** [comment] 2015-06-12 12:35
If anything, changing the original function into this would be best:

Original
````javascript
function fixPlayerSize() {
    if (isNewPlayer()) {
        window.matchMedia = null;
    } else {
        patchDetour();
    }
}
````

Changed fix
````javascript
function fixPlayerSize() {
    window.matchMedia = null;
}
````

**Comment by SuperSajuuk** [comment] 2015-06-13 17:13
I had to take the plunge and switch to the new player, simply because the old player was pushing the content down a bit from the top (meaning a small section at the bottom of content was cut off completely). Are any updates "actually" going to appear, or is this just going to become abandoned? Heard nothing from @YePpHa in ages and no updates in at least a week :/

**Comment by rotemdan** [comment] 2015-06-15 05:28
@Yonezpt Thanks for the solution (would have taken many hours or even days to figure that out myself). I got tired of waiting for YTC to be fixed and instead made a new userscript with the features I considered the most important (and some that were not available in YTC at all) based on my personal preference for customization. I called it "[YouTube Cinema Mode](https://greasyfork.org/en/scripts/10417-youtube-cinema-mode)" (link is to Greasyfork, but might be on GitHub in the future). Here's the current feature list:

* Maximizes player to fit the entire viewport area.
* Auto-hides the top bar on watch pages for maximum space utilization (will only display when mouse hovers over the top of the page).
* Auto-pauses other playing videos (in any tab) when playback is started/resumed (supports both watch pages and channel pages, but not embedded videos at the moment).
* Disables SPF (Structured Page Fragments, AKA red loading bar).
* Auto-expands video description.

Supports the HTML5 player only. Tested with both the latest Firefox and Chrome (using latest Greasemonkey/Tampermonkey). Works with both the old (black/red) player and the newer, transparent one, which can be enabled [here](https://www.youtube.com/testtube) (recommended).

I tried to organize the code so other developers could benefit from the individual features (feel free to copy/paste into your own scripts). Because of duplicate and conflicting behaviors, it doesn't seem to work well alongside YTC though (that would also depend on the particular YTC settings used).

**Comment by KamranMackey** [comment] 2015-06-17 02:53
@YePpHa Are you gonna fix this issue natively in YouTube Center soon or what? Not trying to be mean, but you haven't pushed a commit to YouTube Center in literally over a month. What's going on? I hope YouTube Center isn't being abandoned.

**Comment by Yonezpt** [comment] 2015-06-17 03:02
@KamranMackey I think in Europe, around these months, is the exams season. If he is studying then he is very likely unable to have enough free time to update YTC since some of those exames require the students to study for an entire month non-stop, in some cases up to 2 months.

But that is if he is studying, I am just guessing here so it might be something completely different.

**Comment by SuperSajuuk** [comment] 2015-06-17 07:55
@KamranMackey @Yonezpt Based on his profile pic, he doesn't really strike me as the kind of person who would be studying for exams, but appearances don't tell the whole story ;)

But yes, I'm starting to believe the extension is abandoned, unless he commits something soon. And if it's abandoned, it'll need community involvement to fix things. >_>

**Comment by GarfieldDeepClone** [comment] 2015-06-17 12:25
Don't let that great script die....

**Comment by SnowGabe** [comment] 2015-06-17 13:48
Do you have this issue when using a fullscreen player?

![2015-06-17 16_36_37-ask mkbhd v4](https://cloud.githubusercontent.com/assets/11059234/8208481/82e348ea-1510-11e5-830a-a2ec29d3f8f2.png)

**Comment by GarfieldDeepClone** [comment] 2015-06-29 14:00
Did I miss something? Is there a solution or has the script been abandoned?

**Comment by Yonezpt** [comment] 2015-06-29 14:04
@GarfieldDeepClone A temporary solution has been presented above: https://github.com/YePpHa/YouTubeCenter/issues/1844#issuecomment-111477296

**Comment by foss-** [comment] 2015-07-12 08:19
Can someone update the title? This was not restricted to chrome only but also happened in Firefox (several users did report so).

Also in latest FF 39.0 + YTC dev 528 I have not been seeing this any longer.

**Comment by ireun** [comment] 2015-07-12 08:23
@foss- Done, this will be now a main issue about bugged player resizing, and every duplicate will get closed. ;)

**Comment by Yonezpt** [comment] 2015-07-12 15:39
@foss- This issue has already been fixed in [dev. 526](https://github.com/YePpHa/YouTubeCenter/commit/459265efd4ac72224c70987267f53a6d1865fd25#diff-7f8e8fd9264ba1b0f6bad74a21abad37L10989), it can be closed as far as I can see.

**Comment by ireun** [comment] 2015-07-12 15:57
Sure, if you want feel free to close issues for yourself. ;)

**Closed by ireun** 2015-07-12 15:57 UTC
Labels: bug

**Comment by Wolf68k** [comment] 2015-07-16 15:08
Not fixed yet. Happening in dev.528

**Comment by Yonezpt** [comment] 2015-07-16 15:50
@Wolf68k Can you provide screenshots of the issue? Because there is a very similar one that might be mistaken by this one, however it is being caused by a Firefox setting, not by YTC (see [issue 1812](https://github.com/YePpHa/YouTubeCenter/issues/1812))

**Comment by welwood08** [comment] 2015-07-16 16:05
To offer a second data point, this issue had been fixed for me in Firefox until some time today. The issue resurfaced without me making any change in either YTC or Firefox settings. YTC build 529 fixes it again.
