### ISSUE TITLE
key control of player working propperly

### ISSUE THREAD

**Issue by BiZZKeryear** [YePpHa/YouTubeCenter#1733] opened 2015-05-02 11:56 UTC
The hotkey control of the player can be set up in two was ... that they work on whole site or only in the player itself. (impractical since you have to click in the player each time before you can starting to use keys)

For a very long time you could set it up to work on the whole page but it would ignore key if you are writing a comment.

Now the player reacts when writing a comment and eating up all white spaces. (only effect instead of having a white space in the comment is that the playback toggles)

**Comment by Inyokus** [comment] 2015-05-02 12:54
Duplicate of #1546.

**Closed** 2015-07-10 09:48 UTC
