### ISSUE TITLE
Anyone got the play button on the screen?

### ISSUE THREAD

**Issue by Trueffel** [YePpHa/YouTubeCenter#1368] opened 2015-01-12 12:14 UTC
Using build 461 on chrome 64bit and the html5 player, i recently started to get the play (or sometimes pause) button on the screen after doubleclicking it (going fullscreen or out). I feel like it started when i checked prevent buffer and play (i usually only prevent play on tabs). It goes away when clicking directly on it.

PS: the prevention didnt work, but as i understand, its a known issue (?)

**Comment by ErdeFB** [comment] 2015-01-12 13:24
I occasionally have this on Firefox as well. However, I am not sure if it is a issue with YTC or just the html5 player itself. As I can't reproduce the issue at will, it would be difficult to test.

I don't have either of the options you listed enabled so I doubt they are the cause.

**Comment by tomtom9749** [comment] 2015-01-14 01:59
Happens every few videos for a day or so now for me

**Comment by Yung1683** [comment] 2015-01-14 04:06
Please do not email me again I no longer need that thanks and regards !

yhyung

On 14 Jan 2015 12:59, tomtom9749 <notifications@github.com> wrote:
Happens every few videos for a day or so now for me

---

**Comment by Yonezpt** [comment] 2015-01-17 09:06
Been having this occasionally as well ever since @Trueffel reported it, however it has been happening with YTC disabled too which rules out the possibility of this being something caused by the addon. Youtube has been changing quite a few mechanisms of their player for the past two weeks, it is very likely that this glitch is the side effect of one of those changes.

**Comment by ErdeFB** [comment] 2015-01-17 14:51
As it seems this is not a YTC issue, @Trueffel, could you please close the issue by clicking the "close issue" -button.

**Closed** 2015-02-19 07:53 UTC
