### ISSUE TITLE
Comment Country Flags don't display in newest dev. build (496) [chrome extension]

### ISSUE THREAD

**Issue by random6969** [YePpHa/YouTubeCenter#1610] opened 2015-04-02 00:11 UTC
After updating to the latest dev. version today, I noticed that the country flags in comments no longer display.

**Comment by audjack99aus8** [comment] 2015-04-02 10:33
not showing in firefox as well

**Comment by Inyokus** [comment] 2015-04-03 17:49
Most likely duplicate of #1540.

**Comment by random6969** [comment] 2015-04-16 01:15
This bug still exists in the current dev. version, 501. 
YePpHa, please fix this soon as it was an incredibly useful and interesting added feature, thank you!

**Comment by ireun** [comment] 2015-07-10 09:54
Migrating all issues about country flags not working to one issue, check out issue number "1877".

**Closed by ireun** 2015-07-10 09:54 UTC
Labels: bug
