### ISSUE TITLE
YTC is not compatible with YT's new layout

### ISSUE THREAD

**Issue by Smeagol001** [YePpHa/YouTubeCenter#2309] opened 2016-11-08 07:20 UTC
ytc is not working on most sites other than /watch.....

**Comment by Maverynthia** [comment] 2016-11-08 08:58
I think they broke that too and the "Restore Classic Youtube" doesn't work either.

**Comment by ErdeFB** [comment] 2016-11-08 10:51
What YTC version are you using?

**Comment by gladiac1337** [comment] 2016-11-08 16:18
@Smeagol001 and @Maverynthia are right. Obviously, YouTube launched a new Web UI today which pretty much broke YouTube Center. This is the new design:
![new_greasemonkey_disabled](https://cloud.githubusercontent.com/assets/878225/20106948/20f4f8b4-a5d7-11e6-90be-cfa136fcafa4.png)

And here is what it looks like with YouTube Center enabled:
![broken](https://cloud.githubusercontent.com/assets/878225/20106978/3a427f30-a5d7-11e6-8429-f926ba1e5d32.png)

**Comment by Steffe2** [comment] 2016-11-08 17:14
Yep, same problem here :/ Page doesn't work properly with or without YTC though, clips have problems loading and can't check comments etc (those two are not YTCs fault though).

**Comment by Smeagol001** [comment] 2016-11-08 18:15
using lastest ytv dev build and chrome scriptversion

**Comment by ErdeFB** [comment] 2016-11-08 19:52
I see. The new design hasn't rolled out for me so no wonder I didn't notice anything. @YePpHa if you have time, this is probably going to be a critical issue as the rollout proceeds.

**Comment by ErdeFB** [comment] 2016-11-08 19:57
Actually, duplicate of #2293

**Closed by ErdeFB** 2016-11-08 19:57 UTC
Labels: bug: Layout
