### ISSUE TITLE
Https?

### ISSUE THREAD

**Issue by danilaml** [YePpHa/YouTubeCenter#1353] opened 2015-01-07 22:21 UTC
Sorry, but quick googling didn't help. Where did this option go? And why?

**Comment by Eisys** [comment] 2015-01-08 09:51
Youtube uses HTTPS all the time anyway so the option was removed!

**Comment by danilaml** [comment] 2015-01-08 14:32
It doesn't fore me. If I open https youtube - then everything is fine. But if I just type www.youtube.com it opens with regular connections and all browsing happens with insecure protocol.

**Comment by Eisys** [comment] 2015-01-08 18:24
Hmm, thats weird. If I just type in like that it works fine for me! Im on Chrome beta with the latest DEV version of YTC!
What browser and what YTC version are you using? It might be caused by a setting in your browser perhaps..

**Comment by danilaml** [comment] 2015-01-08 18:48
Chrome 39.0.2171.95
YTC build 461

**Comment by ErdeFB** [comment] 2015-01-09 10:48
This problem is very peculiar as I can't force HTTP even when writing the URL as http://youtube.com on Firefox 36.

**Comment by danilaml** [comment] 2015-01-09 13:49
Strange thing is that with google search everything is fine. It always has https protocol.

**Comment by Yonezpt** [comment] 2015-01-11 09:00
Could you try with Firefox to see if it is something that might be related to your ISP/geographic location or browser related?

**Comment by danilaml** [comment] 2015-01-11 13:59
Well, I've got reply from someone from yt: 
"I have confirmed that this is expected behavior for you at this time. You may wish to use extensions such as SSL Everywhere in order to ensure the usage of SSL for your connection to YouTube.
Sorry for the inconvenience."

**Comment by ErdeFB** [comment] 2015-01-11 14:06
I'm pretty impressed you managed to find their contact info and also receive a reply from them.

Anyway, as this apparently is not a YTC issue, please close this issue report by clicking on the "close issue" -button at your earliest convenience.

**Closed** 2015-01-11 14:07 UTC

**Comment by danilaml** [comment] 2015-04-25 00:23
Sorry for necroposting, Just found something strange/annoying:
all youtube videos in googlesearch are opened via http, (while links to youtube itself are in https).
The most annoying things is that if I click on any element in comment section it reloads page to https.
