### ISSUE TITLE
Videos left-aligned

### ISSUE THREAD

**Issue by deusexcalamus** [YePpHa/YouTubeCenter#1358] opened 2015-01-09 04:18 UTC
Videos randomly started showing up as left-aligned for me, not sure why.
![capture](https://cloud.githubusercontent.com/assets/8674645/5675458/346f8d22-9784-11e4-87d8-9840ab3ffe2f.PNG)

**Comment by fallenstory** [comment] 2015-01-09 06:04
It occurs when you have Dark player background option ticked. I'm not sure why it happens though.

**Comment by ErdeFB** [comment] 2015-01-09 10:46
Duplicate of #1357.

**Comment by Eisys** [comment] 2015-01-09 14:42
I can confirm it too.. But I kind of like it.. It gives more room on the right for a skype convo which is nice. It would be cool if we could have a way to align videos to the right or left with buttons!

**Comment by CathalCraft** [comment] 2015-01-17 01:31
Turn on "Only stage mode" in Player Size. That fixed it for me.

**Comment by fallenstory** [comment] 2015-01-17 01:57
Cheers that worked. @CathalCraft

**Closed** 2015-01-18 09:51 UTC
