### ISSUE TITLE
Youtube video doesn't fit the player window.

### ISSUE THREAD

**Issue by RecklessJames** [YePpHa/YouTubeCenter#1873] opened 2015-06-04 19:11 UTC
I've been getting this issue for a month now, and I'm getting tired of it!

![imgur](http://i.imgur.com/jjzqSVy.jpg)

It looks like that and I can't make it stop.  I tried switching player mode to flash and it fixes it, but then it keeps crashing firefox and it sucks.  I demand this to be fixed NOW!

**Comment by Zarggg** [comment] 2015-06-04 19:14
If you are still using 2.1.7, upgrade to the current [Developer Version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version).

**Comment by Astan92** [comment] 2015-06-04 21:57
Issues is still present in the current developer version for me. I am on Google Chrome Version 43.0.2357.81 (64-bit) on OSX

**Comment by S-ed** [comment] 2015-06-04 22:50
Same here. 525 dev build. Both userscript and xpi versions. Firefox 37.0.2.

**Comment by RecklessJames** [comment] 2015-06-04 23:23
I am using the updated dev build, that is not the issue.  It was fine earlier but now it is not.

**Comment by S-ed** [comment] 2015-06-04 23:57
Seems like YTC ignores inline style:

```
<video src="mediasource:https://www.youtube.com/somerandomsid" data-no-fullscreen="true" class="video-stream html5-main-video" style="width: 640px; height: 360px; left: 0px; top: 0px; transform: none;"></video>
```

**Comment by jasonycw** [comment] 2015-06-05 02:59
The only "temp solution" is to enable the new player from https://www.youtube.com/testtube

Although I don't like that player as it don't show the play status and time all the time, the video fill the player.

**Comment by audjack99aus8** [comment] 2015-06-05 10:09
The new player fixes the problem but it disables autoplay on playlists the same video stats again when you click on the play icon
There is a user script that is better called Resize YT To Window Size  https://greasyfork.org/en/scripts/811-resize-yt-to-window-size

**Comment by Yonezpt** [comment] 2015-06-06 21:19
This issue has been reposted multiple times, please use the search box to avoid more duplicates. The main issue thread seems to be focused here, as well as temporary fix suggestions: https://github.com/YePpHa/YouTubeCenter/issues/1844#issuecomment-106976683

**Comment by RecklessJames** [comment] 2015-06-06 22:11
Thanks, issue resolved.

**Comment by S-ed** [comment] 2015-06-06 23:38
#1844 applies to Chrome. So proper naming for issues is required otherwise duplicates unavoidable.
Searching for term 'resize' gives me 64! opened issues.
I guess the best way is to create new issue with proper title and close each duplicate with link to it.

**Comment by bdawg923** [comment] 2015-06-07 03:21
I demand this to be fixed NOW!

That's funny. The author provides this extension free of charge and works on it for free when he has time. You're in no position to demand anything you ungrateful little person. Especially considering this was discussed in multiple threads. So calm yourself RecklessJames.

**Comment by ireun** [comment] 2015-07-12 08:17
A duplicate of #1844.

**Closed by ireun** 2015-07-12 08:17 UTC
Labels: bug, bug: Layout, duplicate
