### ISSUE TITLE
'This page is asking you if you want to leave'

### ISSUE THREAD

**Issue by deusexcalamus** [YePpHa/YouTubeCenter#1299] opened 2014-12-15 05:40 UTC
Getting this error with devbuild 459 when I go from www.youtube.com/ to www.youtube.com/subscriptions (Just an example, not sure if it happens on other pages)
![prompt](https://cloud.githubusercontent.com/assets/8674645/5431256/8f1eee6e-83ea-11e4-8dda-d777f0887b89.jpg)
Doesn't seem to do it with the extension disabled. Thoughts?

**Comment by nallar** [comment] 2015-01-08 18:10
Proposed solution: show the dialog only for user-initiated settings saves. Anything caused due to caching API results shouldn't show the dialog.

**Comment by Djfe** [comment] 2015-01-08 23:41
@nallar sounds good to me

another way how to achieve it is:
making a customized message like facebook does it:
put js on every link on the page and only let further pages load if there is no unsaved text in a message you were writing (works only on facebook of course and not if you are closing the tab)
->it happens if you write a comment below a post but don't press enter and then try to go to the news feed again or your profile -> skinned blue dialog of facebook appears

**Comment by danilaml** [comment] 2015-01-13 17:04
Why it needs to save something every time? It also does this than you click on link (not only then you close window)

**Comment by FichteFoll** [comment] 2015-01-13 19:09
It saves the results of the video thumbnail preview when you hover on it, so it doesn't have to load those again when that video re-appears.

**Comment by danilaml** [comment] 2015-01-13 19:47
It does something else to. I can easily replicate it. Just click on link on yt and then pres back (for example got from subscription to recommendations and hit back) - the dialogue will appear immediately. However, if you do this by clicking on "My Subscriptions" link and not "bacK" button the dialogue won't show up.

**Comment by Yung1683** [comment] 2015-01-14 04:04
Please do not email me again I no longer that thanks & regards !

yhyung

On 14 Jan 2015 04:04, Danila Malyutin <notifications@github.com> wrote:
Why it needs to save something every time? It also does this than you click on link (not only then you close window)

---

**Comment by Yung1683** [comment] 2015-01-14 04:09
Please do not email me again I no longer need that thanks and regards !

yhyung

On 14 Jan 2015 06:09, FichteFoll <notifications@github.com> wrote:
It saves the results of the video thumbnail preview when you hover on it, so it doesn't have to load those again when that video re-appears.

---

**Comment by Yung1683** [comment] 2015-01-14 04:12
Please do not email me again I no longer need that thanks and regards !

yhyung

On 14 Jan 2015 06:47, Danila Malyutin <notifications@github.com> wrote:
It does something else to. I can easily replicate it. Just click on link on yt and then pres back (for example got from subscription to recommendations and hit back) - the dialogue will appear immediately. However, if you do this by clicking on "My Subscriptions" link and not "bacK" button the dialogue won't show up.

---

**Comment by FichteFoll** [comment] 2015-01-14 15:53
@Yung1683 
It appears that you have either subscribed to this issue or watched the whole repository. You can change your notification settings [here](https://github.com/settings/notifications) or just unsubscribe from this issue / unwatch the repo.

You receiving emails from us is not our fault.

**Comment by Yung1683** [comment] 2015-01-14 23:18
I no longer need your email me thanks !

yhyung

On 15 Jan 2015 02:53, FichteFoll <notifications@github.com> wrote:
@Yung1683
It appears that you have either subscribed to this issue or watched the whole repository. You can change your notification settings [here](https://github.com/settings/notifications) or just unsubscribe from this issue / unwatch the repo.

You receiving emails from us is not our fault.

---

**Comment by danilaml** [comment] 2015-01-14 23:23
So why was this closed? It is still very annoying and happens regularly.

**Comment by Yung1683** [comment] 2015-01-14 23:41
Do not email me again please !

yhyung

On 15 Jan 2015 10:23, Danila Malyutin <notifications@github.com> wrote:
So why was this closed? It is still very annoying and happens regularly.

---

**Comment by TetraSky** [comment] 2015-01-15 00:04
@Yung1683 Look on the Right side, you will see a menu. On that menu there is "Notifications" and below that, there's a big button named "Unsubscribe". Click it. You will no longer receive emails after that.

**Comment by danilaml** [comment] 2015-01-15 00:05
It emails you automatically by github because you are watching this issue/repo and set up your notifications to do so. You already been told how to disable it. Please, read.
I even made a picture for you: http://i.imgur.com/TgZfpUP.png

**Comment by ErdeFB** [comment] 2015-01-15 04:19
@danilaml This was closed probably because it is not a YTC bug per se. I think this should be re-opened for discussion.

And if @Yung1683 still keeps spamming, just report him. He's been told several times how to stop receiving email notifications already. If he keeps up, just report him.

**Comment by Yung1683** [comment] 2015-01-15 05:37
I no longer email me please !!!!!!!

yhyung

On 15 Jan 2015 15:19, ErdeFB <notifications@github.com> wrote:
@danilaml This was closed probably because it is not a YTC bug per se. I think this should be re-opened for discussion.

And if @Yung1683 still keeps spamming, just report him. He's been told several times how to stop receiving email notifications already. If he keeps up, just report him.

---

**Comment by Yung1683** [comment] 2015-01-15 05:40
I no longer email me thanks and regards

yhyung

On 15 Jan 2015 11:05, Danila Malyutin <notifications@github.com> wrote:
It emails you automatically by github because you are watching this issue/repo and set up your notifications to do so. You already been told how to disable it. Please, read.
I even made a picture for you: http://i.imgur.com/TgZfpUP.png

---

**Comment by Tailszefox** [comment] 2015-01-15 10:35
I think it's been closed because it's sort of solved: there's a setting now you can uncheck if you don't want to be warned. I think it hides the problem rather than solve it, though, since it can leave you with corrupted preferences if you close the window while it's saving.

I'm certain it wasn't showing up a few versions ago, though. So either the issue was always there and the warning was added recently, or the warning has been there for a while and there's something that forces YTC to save its preferences more often than before.

**Comment by nallar** [comment] 2015-01-18 01:45
@deusexcalamus @YePpHa  Could you reopen this issue? The current solution is only really a workaround - whatever's causing YT center to be saving settings more than before isn't fixed, or alternately changing the dialog only to popup only when the settings save was user initiated hasn't been implemented.

Currently it's very annoying and on by default, occurring on about 35% of page changes. It's definitely not a good user experience and something needs changed, even if that's only disabling the dialog by default.

If the issue is that interrupting settings saves can sometimes cause them to be lost, I suggest saving the cache completely separately from the other settings instead of having settings (updated irregularly and big issue if lost) and cache(updated regularly, who cares if interrupting a save causes cache to be lost) stored in a single object which gets stringified and saved.

**Comment by YePpHa** [comment] 2015-01-19 16:21
This `feature` has now been replaced. Instead of alerting you that it hasn't finished saving its settings it will now try to save the settings as fast as possible by canceling the throttling and then saving without throttling.

**Closed by YePpHa** 2015-01-19 16:21 UTC
Labels: bug
