### ISSUE TITLE
Comment country flags not showing up

### ISSUE THREAD

**Issue by SumitAgr** [YePpHa/YouTubeCenter#1660] opened 2015-04-13 18:30 UTC
Hi,
The youtube channel owner's country flag is fine but for some time I cannot see the comment country flag showing up. It has been like this for sometime.

**Comment by random6969** [comment] 2015-04-14 05:20
Duplicate of #1610

**Comment by ireun** [comment] 2015-07-10 09:54
Migrating all issues about country flags not working to one issue, check out issue number "1877".

**Closed by ireun** 2015-07-10 09:54 UTC
