### ISSUE TITLE
Incorrect resizing for html5 player

### ISSUE THREAD

**Issue by Hobbix** [YePpHa/YouTubeCenter#1851] opened 2015-05-28 09:59 UTC
![1](https://cloud.githubusercontent.com/assets/8199105/7857479/492d6284-0539-11e5-9db9-88dc5df871cd.png)
![2](https://cloud.githubusercontent.com/assets/8199105/7857481/4c9b5db8-0539-11e5-99b1-5dc57428fd6a.png)
![3](https://cloud.githubusercontent.com/assets/8199105/7857483/4e73125c-0539-11e5-82ed-5ebd845d9050.png)

**Comment by RSully** [comment] 2015-05-28 13:59
Same issue on Safari. All videos I watch are cut off because of how I have my settings :(.

**Comment by Yonezpt** [comment] 2015-05-28 16:58
Duplicate of #1844, temporary workarounds are also available at the end of the linked issue.

**Comment by ireun** [comment] 2015-07-12 08:09
@Yonezpt Is it? The issue there is about the video not taking all of the player space, this one is.. about wrong resizing the timeline, or maybe taking too much space, I'm not sure.

Correct me if I'm wrong..

**Comment by Yonezpt** [comment] 2015-07-12 15:29
It is the same issue, both the canvas and progressbar shared the same problem, which as of a few months ago is no longer existent thanks to a [recent change YouTube made to their player](https://github.com/YePpHa/YouTubeCenter/issues/1844#issuecomment-106102096), so all of the issues related to this and the one I linked no longer exist.

**Closed** 2015-07-17 10:35 UTC
Labels: bug
