### ISSUE TITLE
[Bug?] Unnecessary black fill on right side of 'Large' player sized videos.

### ISSUE THREAD

**Issue by RevolutionGG** [YePpHa/YouTubeCenter#1706] opened 2015-04-29 12:51 UTC
Image here: http://i.imgur.com/rieAihf.jpg

I'm using the Dev Build version #501 on Firefox 37.0.2. I didn't have this problem until FF crashed for some unknown reason.

I can't find any settings in YTCenter to fix this. No doubt that this would be in the 'Player' tab of the settings, but changing colours, changing aspect ratios, and manually setting numbers for sizes hasn't fixed this problem yet.

If I uncheck the 'Large' box in the player size settings (http://i.imgur.com/PP7bbB8.jpg which makes the player uncentred and puts the suggested videos on the right of the player) the black space is gone: http://i.imgur.com/VlGxhFZ.jpg

Is this a bug or just some weird settings conflict?

**Comment by ErdeFB** [comment] 2015-04-29 12:55
Jesus, how many duplicates of this will we get? People, please use the search feature. Heck, you don't even need to do that  much, you actually see all the duplicates before you can create a new issue report.

**Comment by RevolutionGG** [comment] 2015-04-29 12:58
1, actually. I saw 1 other similar to this (#1695), I'm assuming it's related to the youtube update.

**Comment by SINE** [comment] 2015-04-29 14:15
duplicate of
#1695
#1696
#1697
#1705

**Closed** 2015-04-29 16:01 UTC
