### ISSUE TITLE
YoutubeCenter stop working on firefox

### ISSUE THREAD

**Issue by TheColher** [YePpHa/YouTubeCenter#2199] opened 2016-03-05 00:33 UTC
i'm not sure what's wrong

**Comment by frankbuttolph** [comment] 2016-03-05 02:13
the greasemonkey version still works for me but the firefox addon stopped for me as well

**Comment by Fironet** [comment] 2016-03-06 16:41
Likely the same as #2187, which is a dupe of various other issues. Basically new Firefox versions have stopped supporting unsigned addons.

**Comment by pilotrtc** [comment] 2016-03-07 03:29
about:config > setting **xpinstall.signatures.required** to false usually works but this time it doesn't. :-( The menu doesn't even show.

**Comment by Fironet** [comment] 2016-03-07 06:41
The setting will be completely absent in coming versions. The only reason it hasn't affect me is I'm running the Developer version of Firefox which will never had the option removed.

**Comment by ErdeFB** [comment] 2016-03-07 07:25
The active development of this add-on has stopped. Currently the only viable way for FF users is to use the userscript version as Mozilla will stop supporting unsigned add-ons completely in near future.

**Closed by ErdeFB** 2016-03-07 07:25 UTC

**Comment by Myppomeu** [comment] 2016-03-09 00:11
In ESR version xpinstall.signatures.required supported as well as in dev version.
