### ISSUE TITLE
[Request] Subscription Links (in Guide) go to "Videos" Page Option

### ISSUE THREAD

**Issue by RadioActiveLobster** [YePpHa/YouTubeCenter#1587] opened 2015-03-23 18:24 UTC
I'd like to request that an option to have the Subscription link in the left hand drop down guide go to the "Videos" page instead of the channel landing page. 

Currently they just link to the user page, e.g. "https://www.youtube.com/channel/UCy1Ms_5qBTawC-k7PVjHXKQ"

Like with the ability to change where there YouTube logo takes you to, I'd like the ability to have those links go to "https://www.youtube.com/channel/UCy1Ms_5qBTawC-k7PVjHXKQ/videos" instead. 

Essentially just add the ability to add the "/videos" to the end of the URL.

**Comment by KamranMackey** [comment] 2015-03-23 20:17
Alright, hopefully @YePpHa will see this request whenever he comes on. Thanks for the suggestion!

**Comment by Yonezpt** [comment] 2015-03-24 05:59
It has been already requested #898 and listed by the addon Author as well #1014

**Comment by KamranMackey** [comment] 2015-03-24 12:26
Duplicate of #898 and #1014.

**Closed by KamranMackey** 2015-03-24 12:26 UTC
Labels: request: Feature
