### ISSUE TITLE
[Build 525] HTML5 player reloads when forcing the flash player

### ISSUE THREAD

**Issue by Pikachuy** [YePpHa/YouTubeCenter#1823] opened 2015-05-17 08:30 UTC
When forcing the flash player, every time you load a video, a couple of seconds of it play in the new player, then it reloads and shows the flash player. This is mildly annoying, but I'm afraid it might be eating up resources that shouldn't even be a concern. Then again, I don't know much about this so I could be entirely wrong.

**Comment by SuperSajuuk** [comment] 2015-05-17 15:20
That is intentional and is not a bug. YouTube is automatically loading the HTML5 player, but your extension doesn't force Flash Player until the page stops loading. You should really be using the HTML5 player though, as it has the benefit of letting you watch videos at higher frame rates, instead of just a fixed 30fps.

**Comment by Pikachuy** [comment] 2015-05-17 19:32
The only reason I'm not using the HTML5 player is that it doesn't allow the progress bar to hide, and therefore I can only watch a letterboxed version of the video instead of the size I'm currently using with the flash player.

**Comment by SuperSajuuk** [comment] 2015-05-17 20:26
@Pikachuy It hides for me. If it's not disappearing, just move your cursor around the player, then move it off and it should disappear. Make sure you've also set the option to hide the progress bar. HTML5 player is superior to Flash, due to high fps playback, so you should definitely be using it over Flash. :)

**Comment by Hobbix** [comment] 2015-05-17 23:48
In the HTML5 player there is a great problem with tearing (a problem with the vertical sync), if the Windows user is not used (disabled) Aero style. Aero style is bullshit, which immediately disable the normal people
Thus HTML5 player shit, that's why I only use the Flash Player, which supports the vertical sync.

The problem with refreshing the page is very annoying. If possible, try to fix it. Thank you.

**Comment by Yonezpt** [comment] 2015-05-18 15:36
@Hobbix Keep in mind that YouTube intends to drop the flash player support for their website soon, that is why they are moving towards the HTML5 player completely and you won't be able to use their flash player any longer when that time comes.

**Comment by ireun** [comment] 2015-07-17 18:04
Yup, it's not because of YTC.. 

*Closing...*

**Closed by ireun** 2015-07-17 18:04 UTC
