### ISSUE TITLE
randomly forgetting settings

### ISSUE THREAD

**Issue by banther7** [YePpHa/YouTubeCenter#1354] opened 2015-01-07 22:50 UTC
at random the addons forgets the settings i have. im using the latest dev version

**Comment by ErdeFB** [comment] 2015-01-07 23:29
This is a duplicate of #1263. Please check open issues before posting a new one, thanks.

Also, please close this issue report at your earliest convenience.

**Closed** 2015-01-13 00:51 UTC
