### ISSUE TITLE
Info box and playlist too wide.

### ISSUE THREAD

**Issue by eduardog3000** [YePpHa/YouTubeCenter#1763] opened 2015-05-08 21:08 UTC
How it looks now:

![](http://i.imgur.com/gD7R2Vm.png)

How it used to look, how I want it to look, and how it looks now when inspect element is open:

![](http://i.imgur.com/xZK73YF.png)

I am on the newest dev version, it started a couple dev versions ago.

If I make the inspect element console shorter, it becomes wide again.

**Comment by Inyokus** [comment] 2015-05-08 21:28
Duplicate of #1754. More information here: https://github.com/YePpHa/YouTubeCenter/issues/1754#issuecomment-100019340

**Closed** 2015-05-08 21:33 UTC
