### ISSUE TITLE
html5 player video not going in center of screen

### ISSUE THREAD

**Issue by audjack99aus8** [YePpHa/YouTubeCenter#1846] opened 2015-05-27 04:38 UTC
Using the html5 player All of a sudden all videos are going to right of the screen.
DEV BUILD 525 ON FIREFOX

http://i60.tinypic.com/b625b4.jpg

**Comment by Cyguard** [comment] 2015-05-27 04:49
Similar issue, but as seen in the screenshot the player size does not change but the video is squished into the upper left corner of the player.
![untitled3](https://cloud.githubusercontent.com/assets/9603009/7829011/13d7c7d0-03f1-11e5-8a70-16c2722ebae9.png)

**Comment by lolzstuff** [comment] 2015-05-27 05:46
Having the same problem, 525 on Firefox. Only way to make it resize correctly is to switch back to flash, and I really hate flash player.

**Comment by aztectornado** [comment] 2015-05-27 06:34
Same issue running Chrome. Flash player works fine, but the HTML5 one seems to no longer stretch/resize properly. 

Build 525

**Comment by T0m0rr0w** [comment] 2015-05-27 07:15
I can confirm this on Firefox v38.0.1 But i think this might be Google's fault because the same thing started happening to me on an earlier build and upgrading to #525 did not change this. Problably they changed something related to HTML5 (again) wich broke the scaling.

**Comment by Rockeer** [comment] 2015-05-27 08:23
Same problem here on Chrome HTML5 player :/

**Comment by CathalCraft** [comment] 2015-05-27 09:14
Same problem using Firefox and dev #525.
http://puu.sh/i2eqM/597dccb827.jpg

**Comment by SnowGabe** [comment] 2015-05-27 09:45
Latest 525 developer build:
![2015-05-27 12_45_09-witcher 3 mods 1](https://cloud.githubusercontent.com/assets/11059234/7833280/3fb96692-046e-11e5-82b0-b79701b7392c.png)

**Comment by LiamBM** [comment] 2015-05-27 10:01
Same on Chrome and Safari. Youtube did just update their site a few hours ago though.

**Comment by Humanitarian1** [comment] 2015-05-27 11:13
It's back!

This was one of the issues that made me move to the dev version, seems it's followed me here.

it's only on the html5 player, I'm on version 525

**Comment by SuperSajuuk** [comment] 2015-05-27 11:39
@Humanitarian1 It's a bug from today's YouTube update, not a bug in YouTube Center itself. Nothing you can do except wait for @YePpHa to create the fix.

**Comment by DeeboDK** [comment] 2015-05-27 15:20
Youtube needs to stop fiddling with crap. It just causes all kinds of headaches.

**Comment by KamranMackey** [comment] 2015-05-27 16:15
Duplicate of #1844.

**Closed by KamranMackey** 2015-05-27 16:15 UTC
Labels: duplicate
