### ISSUE TITLE
HTML5 player screwed up again.

### ISSUE THREAD

**Issue by TheCuza** [YePpHa/YouTubeCenter#1946] opened 2015-07-16 14:36 UTC
#1844 is happening again, and it just recently got fixed too.
What's more, using the redesigned player from Testtube no longer fixes the issue like it did before.
Does Youtube pay someone to read this github all day and tell them how to screw us over or what?
Back to flash player for me, I guess.

**Comment by T0m0rr0w** [comment] 2015-07-16 14:38
Yes just noticed this as well. Build #528 Dev edition on Firefox 39.0
let's just hope no workarounds are nessesary this time from users and that YePpHa can issue a fixed build soon...

**Comment by LRFLEW** [comment] 2015-07-16 14:45
I can confirm this is happening on Safari as well. Using Safari 8.0.7 and YTC 528

**Comment by nivao** [comment] 2015-07-16 15:01
Same thing here. Latest Firefox and YTC 528. It was fine a few hours ago.

**Comment by Stalast** [comment] 2015-07-16 15:04
Same here on dev version Build #528

**Comment by Wolf68k** [comment] 2015-07-16 15:10
Still happening in dev.528 FF37 here

**Comment by gapmeister11** [comment] 2015-07-16 15:10
Same thing on Opera 30.0 and dev version 528.

**Comment by SnowGabe** [comment] 2015-07-16 15:44
A duplicate of #1945.

**Closed** 2015-07-16 15:51 UTC
Labels: bug, bug: HTML5
