### ISSUE TITLE
Dark Player Background no longer works

### ISSUE THREAD

**Issue by bjornenalfa** [YePpHa/YouTubeCenter#1711] opened 2015-04-29 18:30 UTC
I am using FireFox 37.0.2 and YouTubeCenter Dev version 503. The Dark Player Background hasn't been working for a couple of days.

**Comment by deusexcalamus** [comment] 2015-04-29 18:33
Having this issue as well. FF 38,  YTC dev 503.

**Comment by yoshinatsu** [comment] 2015-04-29 19:19
Yeah... the update seems to have fixed the misaligned player...
But unfortunately, YouTube seems to have broken the dark background.

**Comment by NicotherZ** [comment] 2015-04-29 23:32
Possible to fix it or dark background is completely broken ?

**Comment by aztectornado** [comment] 2015-04-30 02:02
duplicate of #1696

**Comment by ImmortalKnight** [comment] 2015-05-01 21:24
i also have this issue. and if i disable youtube center, dark background works but the alignment + the black bar bug (something like  #1695 )returns. (new transparent player enabled)

**Comment by leandroprz** [comment] 2015-05-01 23:06
I'm also having this problem on Chrome 42.0.2311.135 m (64-bit) / Win 8.1 x64

**Closed** 2015-05-03 10:20 UTC
