### ISSUE TITLE
HTML5 player blink during video load

### ISSUE THREAD

**Issue by emicom** [YePpHa/YouTubeCenter#1505] opened 2015-02-26 08:20 UTC
HTML 5 player twinkle during video load. When the video is fully loaded stops and play normally. It happen since yesterday. Checked on different computer (with the same Pale Moon configuration) with the same result. The blink is like picture zoom in/out.

**Comment by ErdeFB** [comment] 2015-02-26 12:37
Most likely duplicate of #1497.

**Comment by Puk4400** [comment] 2015-02-26 14:40
Nah i don't think it's duplicate. He says the picture zooms in/out and not bounce. Does it persists when the video is paused? Does it looks like this http://i.imgur.com/MWIVpIz.gif ?
Try going into settings and on player tab, at auto-hide bar chose different options and see if that does anything.

**Comment by ErdeFB** [comment] 2015-02-26 14:44
It is reasonable to speculate the issue is the same as he is describing two completely different things by first saying it blinks as in, on and off, and then claims it zooms in and out and yet gives the impression he is not describing two different issues, but one.

Anyway, best is to see what the poster replies.

**Comment by Puk4400** [comment] 2015-02-26 14:51
It could be the same, my bad, i have had any issue with the last version (489) and just now i saw the issue mentioned in my original post persist. I re-opened the thread just in case.

**Comment by emicom** [comment] 2015-02-26 17:48
Yeah, it is on ver 489, didn't have this problem with older versions. Once the video is fully loaded everything goes fine. Now when I read the post  #1497 I see that others have the same problem. And noticed that sometimes pic goes in/out, other time goes bounced. Checked the task manager - during the video load the processor is 100%. 3Gh Pentium to 100%? Memory is OK - almost empty. Pale Moon store html5 videos on separated space. Shall I enlarge this space? Now is 10140 KB (double than the default).

**Comment by emicom** [comment] 2015-02-26 18:41
It doesn't happen every time, but happen every time when the video is on tab. On single window/tab is ok so far.

**Comment by Yonezpt** [comment] 2015-02-26 21:15
Probably related to this issue: https://github.com/YePpHa/YouTubeCenter/issues/1504

Can you try following the last steps mentioned in the linked issue?

**Comment by emicom** [comment] 2015-02-27 15:16
Yep, with the latest Build #490 seems to be everything OK.
Thanks to the developers/programmers.

**Comment by emicom** [comment] 2015-02-27 16:10
Sorry to say, but the problem stay. It doesn't happen every time, but to say - every second video is zoomed in/out during video load.

**Comment by Yonezpt** [comment] 2015-02-27 16:17
Perhaps you could do what I suggested in my last reply then.

**Closed** 2015-03-02 12:57 UTC
