### ISSUE TITLE
463 broke everything

### ISSUE THREAD

**Issue by emm980** [YePpHa/YouTubeCenter#1387] opened 2015-01-19 17:04 UTC
So, 30 min ago I got the dev build 463 and the whole thing broke down.
I was mostly using the resizing feature and the autostop.

Now the resizing doesn't work at all. the player is still small even if YTC is set to Fit to content and it's largish in size, as I've set it up, almost whole screen. I've set the player to 980px but it's only 850.

Autoplay doesn't fire on every instance and it's not the HTML5 bug, I've set HTML5 video disabled through an extension. The player always load in Flash (forced flash).

Config button is missing from the pages, I can find it in settings page, but not on all pages, or the user bubble menu.

**Comment by YePpHa** [comment] 2015-01-19 17:06
Update to 466. Dupe of #1386.

**Closed** 2015-01-19 17:06 UTC
Labels: bug, duplicate

**Comment by KDsMax** [comment] 2015-01-19 17:13
Running 466 and still have this same issue.

**Comment by YePpHa** [comment] 2015-01-19 17:35
Try updating to 467.

**Comment by YePpHa** [comment] 2015-01-19 17:36
If you're still experiencing the issue dump your console (CTRL + SHIFT + J and CTRL + SHIFT + K).
