### ISSUE TITLE
Subscriptions page changed

### ISSUE THREAD

**Issue by JaykeBird** [YePpHa/YouTubeCenter#1641] opened 2015-04-10 22:38 UTC
So I logged into YouTube today, and I got this: http://i.imgur.com/LbkzpG5.jpg

It seems that YouTube changed how the subscriptions page looks (unfortunately... I would've preferred sticking with the grid layout). Here's how it appears without YTC: http://i.imgur.com/EKRPuFq.png

Running Developer Version 497, Firefox 37.0.1

**Comment by deathdragon1987** [comment] 2015-04-10 22:44
Same here. Running the latest version of chrome (43.0.2357.10 dev-m (64-bit)) and extension 497. http://i.imgur.com/cAjQV3U.jpg

**Comment by ErdeFB** [comment] 2015-04-10 22:44
Duplicate of #1640.
Dude. That was the most recent issue report there was. You have no excuse.

**Comment by JaykeBird** [comment] 2015-04-10 22:45
Oh, I'm sorry! I should've taken a look. That's my fault.

**Closed** 2015-04-10 22:48 UTC
